### ISSUE TITLE
Dropdown Alert Behind IOS router flux navbar (React-Navigation)

### ISSUE THREAD

**Issue by SheppardX** [testshallpass/react-native-dropdownalert#102]
#### Issue Description

On IOS The Dropdown Alert is behind the NavBar from router flux using React-Navigation

#### Steps to Reproduce / Code 

router flux and dropdown alert

#### Expected Results

Dropdown Alert behind Navbar

### Additional Information

* React Native version: 0.50.1
* react-native-dropdownalert version: 3.1.2
* Platform(s) (iOS, Android, or both?): IOS

**Comment by juan-manuel-alberro** [comment]
I had the same issue, just move your component definition on top of the router and that's it.

**Comment by testshallpass** [comment]
Please see: Drop down alert & Stack Navigator #73
