### ISSUE TITLE
Changing the icons

### ISSUE THREAD

**Issue by lehmannsystems** [testshallpass/react-native-dropdownalert#104]
#### Issue Description

I am wondering the best way to change the icons used in the alerts.

#### Steps to Reproduce / Code Snippets

Straightforward

#### Expected Results

Default icons used

### Additional Information

* React Native version: 0.50.4
* react-native-dropdownalert version: 3.1.2
* Platform(s) (iOS, Android, or both?): both

**Comment by jack2684** [comment]
+1.

There is an `imageSrc` property. But would be great if there is a way to submit a customized component. (image is more expensive)

**Comment by mafiusu** [comment]
Is there any way not to show the icons in the alerts?

**Comment by PARAGJYOTI** [comment]
Please add support to react-native-vector-icons . It's the icon pack that everyone uses . Image isn't preferable so much..

**Comment by ma-pe** [comment]
@jack2684 
I agree, supporting Custom Components would be a great thing.

@PARAGJYOTI 
Though, you can use react-native-vector-icons. See section "Usage as PNG image/source object" for details: https://github.com/oblador/react-native-vector-icons#usage-as-png-imagesource-object

**Comment by testshallpass** [comment]
I think it's a great idea to provide more flexibility on this. It's too strict as it stands. I think adding a `renderImage` prop to override the image component by allowing passing a react element would work wonders.

As it was stated you would use the `imageSrc` prop to override the image and type `custom` for it to be used.

**Comment by testshallpass** [comment]
I want to add if using the cancel button you only need to change the `cancelBtnImageSrc` prop and it would apply for all types.

**Comment by ma-pe** [comment]
@testshallpass I'd like that! feel free to get in touch if you need support :-)

**Comment by testshallpass** [comment]
Closing as it's been answered but look for development to make it better in #106

**Comment by maharjanaman** [comment]
@testshallpass can we render different image with renderImage prop based on alert type?
