### ISSUE TITLE
Automatically autoclosing even after closeInterval={0}

### ISSUE THREAD

**Issue by jayeshjain24** [testshallpass/react-native-dropdownalert#108]
#### Issue Description

The dropdown auto closes immediately after appearing. Also closeInterval doesnt seem to be working, not even the default.

#### Steps to Reproduce / Code Snippets

I have placed the component at the bottom of my dom tree. 
 <View>
          <DropdownAlert
          closeInterval={0} 
          ref={ref => this.dropdown = ref} 
          showCancel={true}
          tapToCloseEnabled={true}
          />
        </View>

#### Expected Results
Dropdown should hold on till the user taps on it.

### Additional Information

* React Native version: 0.51.0
* react-native-dropdownalert version: 3.1.2
* Platform(s) (iOS, Android, or both?): Android

**Comment by testshallpass** [comment]
I was not able to reproduce. 
![android-close-demo](https://user-images.githubusercontent.com/7293079/35771459-40a85f92-08fb-11e8-9373-a10440739e33.gif)

**Comment by jsaucedo** [comment]
Hey, did you find the reason for your problem? I'm experiencing the same but on iOS.

**Comment by testshallpass** [comment]
@jsaucedo Can you share a snippet of DropdownAlert? Also, describe anything else that was not stated in original description?
