### ISSUE TITLE
Providing multiple errors in one alertWithTyp() function call throws a warning

### ISSUE THREAD

**Issue by VicFrolov** [testshallpass/react-native-dropdownalert#115]
#### Short Description
I've noticed that if I pass an array of errors, e.g. ["password field is blank", "password fields do not match"], it works perfectly, as I set the numOfLines to the length of the array, and it shows the data appropriately.

However, I am getting a warning "DropdownAlert: Message is not a string". I wanted to know if I should be passing the data differently, or if this requires a PR, and an array of strings is indeed valid.

#### Steps to Reproduce / Code Snippets / Usage

With the example source code, change the alertWithType line to:

`this.dropdown.alertWithType('error', 'Error', ['Error 1', 'Error2', 'Error3');`

and

```
      <DropdownAlert
        ref={ref => (this.dropdown = ref)}
        messageNumOfLines={3}
      />
```

#### Expected Results

No Warning being thrown

### Additional Information

* React Native version: 0.52.0
* react-native-dropdownalert version: 3.3.0
* Platform(s) (iOS, Android, or both?): ios
* iOS version: ios 11
* Android version: N/A

**Comment by VicFrolov** [comment]
Got it, how would you recommend passing multiple errors, where each error is on a separate line? With an array, it does this for me for free, otherwise the error looks instead of:

```
First Error
Second Error
Third Error
```

like this:
`First Error, Second Error, Third Error`

**Comment by testshallpass** [comment]
I haven't tried it but you can maybe get away with ```first error\nsecond error\nthird error``` and set number of lines to 0 (unlimited for iOS)

**Comment by VicFrolov** [comment]
I think you wold agree that this wouldn't be an optimal approach, and should be done under the hood. I personally believe (and could be wrong) that a more intuitive approach is to allow passing in an array of errors, where the number of lines is the length of the array. I'd be happy to make a PR if you agree with this perspective. The down side of course is if you are passing an error as a simple string, vs an array with one item, where one string is more intuitive. Having said that, I still find an array of `n` amounts of errors, that defaults number of lines to be a superior implementation.

**Comment by testshallpass** [comment]
I am going to leverage the discussion and make an enhancement to the title and message parameters. Basically, in a way to be more defensive and flexible.

**Comment by testshallpass** [comment]
**Acceptance criteria**
* Support `array` of messages.
* One message per line.
* `array.length` is fed to `numberOfLines` for `Text` prop.
* `messageNumberOfLines` overridden if message array is present.
* Warn if message(s) can not be converted to strings.
* Backwards compatibility with message as an object (most likely a string).

**Comment by testshallpass** [comment]
I'm closing based on previous comment and no bandwidth to work on it. In `4.0.0` you can provide array as title and message that is converted to a joined string (see: `getStringValue`), however it does not automatically adjust `numberOfLines` which can be configured on the implementer side. For example, `numberOfLines` set to 0 will be unlimited on iOS and set it to big number on Android and should be okay. Plus. if you want to create newlines you can add `\n` to title or message, now I haven't tried it but I assume it works as expected.
