### ISSUE TITLE
Call alertWithType outside of components (sagas, external functions, etc...)

### ISSUE THREAD

**Issue by andreystarkov** [testshallpass/react-native-dropdownalert#117]
Can i call alertWithType somewhere in external functions?

For example:

```js
export function * getSomething (api, action) {
  const response = yield call(api.getSomething)
  if (response.ok) {
    alertWithType('success', ...)
    ...
  } else {
    alertWithType('error', 'Error', response.problem)
    ...
  }
}
```

**Comment by bgeveritt** [comment]
@andreystarkov - I've created a repository that provides a sample on how to:

1. Create and wire a custom "Alert" component, utilizing react-native-dropdownalert
2. Trigger alerts "locally" from a component
3. Trigger alerts "externally" from a JavaScript file

https://github.com/bgeveritt/AlertComponentSample

FYI - I've only tested this on iOS

**Comment by andreystarkov** [comment]
That's awesome! Thanks

**Comment by testshallpass** [comment]
Closing, Thanks again @bgeveritt
