### ISSUE TITLE
Message dropdown very slow when start showing & closing & after closed it create space below android status bar.

### ISSUE THREAD

**Issue by panhna** [testshallpass/react-native-dropdownalert#118]
#### Short Description

![ezgif-4-281776d927](https://user-images.githubusercontent.com/5246440/36653619-e870d3ea-1ae8-11e8-94af-861e57f3ca73.gif)

### Additional Information

* React Native version: 0.52.0
* react-native-dropdownalert version: 3.3.0
* Platform(s) (iOS, Android, or both?): Redmi Note 4X - 6.0
* Android version: 6.0

**Comment by ingeniero92** [comment]
Me too. Only Android with Chrome debugger enabled. Try to disable debugger or run the app without debug mode.

**Comment by testshallpass** [comment]
Hi @panhna Are you transitioning and then invoking it? Please provide some steps.

**Comment by testshallpass** [comment]
@panhna Try out `useNativeDriver` prop introduced in `3.3.1` and see if that helps.

**Comment by panhna** [comment]
thank @testshallpass. after i post the problem. i try to change some code in DropdownAlert.js to use useNativeDriver = true, instead of useNativeDriver=IS_IOS & it work well on performance it slow anymore. but i'm forget to reply back.

so i try the new version soon.

**Comment by panhna** [comment]
@ingeniero92 thank for advise. but i cant. i dont know why. The previous project it's working fine to run the app without debug. but for the new project it very strange. everything wrong the app very slow on load ( i use AsyncStorage on first load), event click is not working, keyboard not show ...

I dont know yet about the problem. may be react-native it self or my code.

**Comment by testshallpass** [comment]
@panhna It sounds to me you might be blocking the UI thread. Maybe try to run the AsyncStorage routine on a background thread or `componentDidMount`. Also, according to docs: 
> On Android, AsyncStorage will use either RocksDB or SQLite based on what is available.

**Comment by panhna** [comment]
thx @testshallpass. now i can solve the problem that app cannot run without debug. 
by remove console.* it's work fine.

**Comment by testshallpass** [comment]
@panhna Ok yeah **Remote JS Debugging** you need to have browser console and the emulator or simulator in the foreground.
