### ISSUE TITLE
Custom image per alert type

### ISSUE THREAD

**Issue by lucianomlima** [testshallpass/react-native-dropdownalert#120]
Turns possible to user set an image for an alert type. Example: custom images for error and success alerts.
Can be new props or an options param for alertWithType method.

**Comment by testshallpass** [comment]
@lucianomlima  If you want you can use `imageSrc` prop and pass `custom` type to change the image in the alert.

**Comment by lucianomlima** [comment]
I know... I use custom type but it would be interesting to be able to have custom image for alert types.

**Comment by testshallpass** [comment]
true something like the errorImageSrc, etc, it would make it a bit easier. I welcome a PR.

**Comment by testshallpass** [comment]
No worries on the testing I will follow up with a tiny patch on that end. Also, thanks.

**Comment by lucianomlima** [comment]
Ok! I try to send a PR

**Comment by lucianomlima** [comment]
```js
  getSourceForType(type) {
    switch (type) {
      case 'info':
        return this.props.infoImageSrc || require('./assets/info.png');
      case 'warn':
        return this.props.warnImageSrc || require('./assets/warn.png');
      case 'error':
        return this.props.errorImageSrc || require('./assets/error.png');
      case 'success':
        return this.props.successImageSrc || require('./assets/success.png');
      default:
        return this.props.imageSrc;
    }
  }
```
This is good for you?

**Comment by testshallpass** [comment]
It's good but can be taken a small step further with the props as the return and the `defaultProps` is the asset. And so: `return this.props.infoImageSrc`

**Comment by lucianomlima** [comment]
Ok. I did change. What I have to put for default in Readme for these new props?

**Comment by testshallpass** [comment]
Basically, `infoImageSrc` would be `require('./assets/info.png');` and etc. See `cancelImageSrc` prop.

**Comment by chhornponleu** [comment]
This feature should support version 2.x as well
