### ISSUE TITLE
StatusBar is removed after dropdownalert is triggered.

### ISSUE THREAD

**Issue by gertvdkolk** [testshallpass/react-native-dropdownalert#122]
#### Short Description

When a dropdownalert shows, the StatusBar hides and won't return to the screen.
![gif1 ](https://i.imgur.com/3TNYJT7.gif)
perhaps a better example: 
![gif2](https://i.imgur.com/2lCUKgS.gif)

This can be fixed with ```updateStatusBar={false}``` but then the StatusBar does not change color when the alert is triggered.
![gif3 ](https://i.imgur.com/9y82r2A.gif)

I set the StatusBar as far up the component chain as possible. (Inside the AppWithNavigation component inside index.js)
```
// AppWithNavigation
return (
      <View style={{ flex: 1 }}>
        <StatusBar backgroundColor={globalStyles.$primaryColor} StatusBar="light-content" />
        <Navigator navigation={navigation} />
      </View>
    );

// index.js
return (
      <Provider store={store}>
        <PersistGate persistor={persistor}>
          <Root>
            <AlertProvider>
              <AppWithNavigation />
            </AlertProvider>
          </Root>
        </PersistGate>
      </Provider>
    );
```

This is inside my return method of AlertProvider.js ( I played around a little trying to solve this issue )
```
<View style={{ flex: 1 }}>
        {React.Children.only(this.props.children)}
        <DropdownAlert
          // defaultTextContainer={{ padding: 10, paddingTop: 30, marginHorizontal: 5 }} // iPhone X
          // elevation={4}
          translucent // android
          // updateStatusBar={false}
          useNativeDriver
          inactiveStatusBarBackgroundColor={globalStyles.$primaryColor}
          ref={(ref) => {
            this.dropdown = ref;
          }}
        />
      </View>
```

My question:
Is this a bug, or am I missing something?

### Additional Information
I am using Expo, Native-base (could be important to know)
* "react-native": "https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz",
* react-native-dropdownalert version: "^3.4.0"
* Platform(s) (iOS, Android, or both?): Tested only on Android
* iOS version: -
* Android version: SDK 25.0.0 (emulator) / Android 7.0 (Samsung galaxy s6)

**Comment by testshallpass** [comment]
what version of react-native?

**Comment by gertvdkolk** [comment]
This is version 0.51 of react-native.

**Comment by testshallpass** [comment]
I think this might be a side effect of ```SafeAreaView```. I'm investigating.

**Comment by gertvdkolk** [comment]
For now I fixed this with a very messy workaround. 
I'm adding a marginTop to all of my headers styles if a dropdownmessage has been triggered somewhere in my application.. (super ugly, because I need to store this 'dropdownHasOccurred' prop in my appState)
🤕 

`marginTop: hasError ? statusbar.currentHeight : 0`

**Comment by socheat1994** [comment]
hi @testshallpass , did you fixe this issue at react-native-dropdownalert version: "^3.5.0" ? :)

**Comment by tonnenpinguin** [comment]
I'm a bit late to the party, but it seems like I'm running into the same issue.

Once the Dropdown alert is triggered it starts adding padding to all views, even after it is closed.

**Comment by Terkhos** [comment]
Do we have any updates on this? I'm experiencing the same issue on RN 0.61 and plugin version 4.2.0

**Comment by MursiDirect** [comment]
Any solution yet? I still have this issue, RN 0.64 and "react-native-dropdownalert": "^4.3.0"

**Comment by ZohaibAhmad786** [comment]
pass this **inactiveStatusBarBackgroundColor** props to dropdownalert and assign the default status bar color
`<DropdownAlert  inactiveStatusBarBackgroundColor={colors.primary} ref={alertRef} />`
