### ISSUE TITLE
Android statusbar showing on top of alert

### ISSUE THREAD

**Issue by bengyles** [testshallpass/react-native-dropdownalert#127]
#### Short Description

When showing the alert on Android, the alert is shown below the statusbar so it has a grey hue over it as shown in the picture below
![screenshot_1522337062](https://user-images.githubusercontent.com/9031491/38097671-47f272c4-3376-11e8-9921-c1edec61f8f7.png)

#### Steps to Reproduce / Code Snippets / Usage

- Create a RN app with expo
- Add react-native-dropdownalert so that an alert can be shown
- test on Android

#### Expected Results

The alert shows on top of the statusbar.

### Additional Information

* React Native version: 0.52.0
* react-native-dropdownalert version: 3.4.0
* Platform(s) (iOS, Android, or both?): Android only
* iOS version: /
* Android version: at least 6 and 7

**Comment by pavermakov** [comment]
You can easily fix it by using the following prop: 
`defaultContainer={{ padding: 8, paddingTop: StatusBar.currentHeight, flexDirection: 'row' }}`

**Comment by pavermakov** [comment]
<img width="485" alt="screen shot 2018-04-04 at 21 55 49" src="https://user-images.githubusercontent.com/10779996/38328226-fe3cce4a-3852-11e8-9e59-16b6d61799bd.png">

**Comment by bengyles** [comment]
@pavermakov 
It works, thank you!

**Comment by jakeOliv** [comment]
@pavermakov where to put this code please? I am facing similar problem!

**Comment by testshallpass** [comment]
@pavermakov Thanks. @jakeOliv add the defaultContainer prop (as stated before) to DropdownAlert instance.

**Comment by mMarcos208** [comment]
I have the same problem.

`<DropdownAlert ref={ref => this.dropdown = ref} defaultContainer={{ padding: 8, paddingTop: StatusBar.currentHeight, flexDirection: 'row' }}/>`

Code StatusBar

`<StatusBar translucent backgroundColor={backgroundColor} {...props} />`

**Comment by whittlem** [comment]
I have the same issue. I don't want the alert showing below the StatusBar. I want it to show from the top of the screen over the StatusBar like it does with IOS.

**Comment by whittlem** [comment]
@testshallpass can you re-open this? This still isn't resolved.

**Comment by hieu292** [comment]
set in the props: updateStatusBar={false} will fix it. https://github.com/testshallpass/react-native-dropdownalert/blob/master/docs/PROPS.md#statusbar
