### ISSUE TITLE
Support for ReactJS PWA?

### ISSUE THREAD

**Issue by MichelDiz** [testshallpass/react-native-dropdownalert#128]
#### Short Description

I started working on a Lite version (before I even finished a native one) I use this DropDownAlert on the native. As I want to "mimic" the native version for PWA I would like to know if ReactJS is supported.

I tried to use it, but it gives errors. I'm running React-Native-Web.

#### Steps to Reproduce / Code Snippets / Usage

npx create-react-app
yarn add  react-native-dropdownalert

#### Expected Results

If it's pure JS, should work out-of-the-box.

### Additional Information

* React Native version: undefined
* react-native-dropdownalert version: last
* Platform(s) (iOS, Android, or both?): Web
* iOS version: undefined
* Android version: undefined

**Comment by testshallpass** [comment]
I do not plan to support PWA.
