### ISSUE TITLE
Android: Status bar colour change delay on close

### ISSUE THREAD

**Issue by cvarley100** [testshallpass/react-native-dropdownalert#133]
#### Short Description

When the dropdown alert closes, there is a delay before the Android status bar backgroundColor returns to the inactive colour.

#### Steps to Reproduce / Code Snippets / Usage

```
<DropdownAlert
    ref={onRef || this.refFunc}
    successColor="#009f3f"
    errorColor="#A10702"
    errorImageSrc={errorIcon}
    successImageSrc={successIcon}
    warnImageSrc={warnIcon}
    infoImageSrc={infoIcon}
    titleStyle={styles.dropdownTitle}
    defaultTextContainer={styles.dropdownTextContainer}
    messageStyle={styles.dropdownMessage}
    imageStyle={styles.dropdownImage}
    inactiveStatusBarStyle={statusBarStyle}
    inactiveStatusBarBackgroundColor={backgroundColor}
    closeInterval={closeAfter}
    tapToCloseEnabled={this.props.hasConnection}
    translucent
/>
```

#### Expected Results

Status bar background colour should update as the modal closes.

### Additional Information

* React Native version: 0.51.0
* react-native-dropdownalert version: 3.4.0
* Platform(s) (iOS, Android, or both?): Android
* Android version: Any

**Comment by testshallpass** [comment]
There should be a delay essentially it's to match the close animation and I think PR #129 tries to move it out of the timeout and potentially fixing it. I need to try out the changes to be certain.
