### ISSUE TITLE
Not visible when react-native-modal is open, with a higher zIndex

### ISSUE THREAD

**Issue by VicFrolov** [testshallpass/react-native-dropdownalert#134]
#### Short Description

I am using react-native-modal, with a zIndex of 9, and react-native-dropdownalert with zIndex of 10. It seems to not appear above the react-native-modal unfortunately. I have also tried this with a regular Modal from react-native.

#### Steps to Reproduce / Code Snippets / Usage

Have a view using the react-native-modal that takes the full screen. Call the dropDownAlert.

#### Expected Results

drop down alert visibility. Unfortunately, not visible.

### Additional Information

* React Native version: 0.55.4
* react-native-dropdownalert version: ^3.3.0
* Platform(s) (iOS, Android, or both?): iOS
* iOS version: 11.3

**Comment by testshallpass** [comment]
Try <DropdownAlert /> as last element of document tree inside the modal component.

**Comment by testshallpass** [comment]
close stale
