### ISSUE TITLE
Navigation with DropdownAlert

### ISSUE THREAD

**Issue by Baqaisooo** [testshallpass/react-native-dropdownalert#135]
I want to show that drop down alert to the user after when moving from page to another while that page loading

**Comment by testshallpass** [comment]
@Baqaisooo I would try adding a prop to destination page where DropdownAlert is located and before or in a timeout invoke the DropdownAlert before navigating.

**Comment by testshallpass** [comment]
I hope it helps. Closing.

**Comment by vinayakvinayam** [comment]
is it done? what prop should i use?  can u show me a example?
