### ISSUE TITLE
Pass some properties down to the Label/Text component

### ISSUE THREAD

**Issue by msevestre** [testshallpass/react-native-dropdownalert#137]
#### Short Description

I would like to pass some properties down to the text component that is used inside the Label. 
The Label as the `textProps` props that we can use (https://github.com/testshallpass/react-native- dropdownalert/blob/master/label.js#L10) but there is no way to set if from the outside.

In my use case, I'd like to be able to pass the [allowFontsScalling](https://facebook.github.io/react-native/docs/text#allowfontscaling) prop to the text to ensure that the text does not resize when user are using extra large fonts. 

It would be sufficient to define a textProps property that would be optional that would be applied to all Labels

**Comment by testshallpass** [comment]
**Acceptance criteria**

- Add `titleTextProps` prop.
- Add `messageTextProps` prop.
- Pass these to label component.
- Update README.

Test integration with existing `numberOfLines` prop.
