### ISSUE TITLE
Application hangs when calling a function that logs the dropdown component

### ISSUE THREAD

**Issue by jrrcdev** [testshallpass/react-native-dropdownalert#138]
#### Short Description

Application hangs, like when on a loop, using on Expo when calling a function that logs the dropdown component, don't know why not now. Not tested without expo.

#### Steps to Reproduce / Code Snippets / Usage

1. Create a react native app using create-react-native-app {your app name}

2. Install react-native-dropdownalert.

3. Change the App.js adding a function that logs the dropdown component, "console.log(this.dropdown)

4. The app stop working

#### Expected Results

The app logs the dropdown components

### Additional Information

* React Native version: 0.55.2
* react-native-dropdownalert version: 3.5.0
* Platform(s) (iOS, Android, or both?): Android
* Android version: 6.0 and 8.0

**Comment by drewandre** [comment]
I'm also seeing this when I set the dropdown component's ref to my redux state... really strange. I won't be able to use the library because of this since I need a modal style dropdown that can be controlled with redux. 

- React Native version: 0.57
- react-native-dropdownalert version: 3.5.0

**Comment by testshallpass** [comment]
@jrrcdev Whats your use case to need to log the component? Or you purely testing it's existence?

**Comment by testshallpass** [comment]
Closing as stale
