### ISSUE TITLE
Implementing accessibility via custom renderers not possible on iOS

### ISSUE THREAD

**Issue by ryanhomer** [testshallpass/react-native-dropdownalert#139]
#### Short Description

In order to implement accessible text and buttons that work with VoiceOver, I implemented the `renderMessage` and `renderCancel` props so that I could use View props such as `accessible`, `accessibilityLabel`, `accessibilityTraits`, etc. in appropriate places. Along with a "sticky" alert (one that doesn't close on its own), this works well on Android.

However, on iOS this does not work due to the outer `TouchableOpacity` that encompasses the entire alert. If `accessible` is set to `false` for this component, iOS then allows the inner components that have `accessible` enabled to be utilized by VoiceOver.

As an aside, it should also be noted that, as is, with VoiceOver on, there is no way to dismiss a sticky alert via the close button. It is simply not selectable. I also tried with the pan responder enabled but I am unsure how to slide up when VoiceOver is enabled.

#### Recommendations

The simply **one-line fix** seems to be to simply add `accessible={false}` to the [`TouchableOpacity` component in the main `render` function](https://github.com/testshallpass/react-native-dropdownalert/blob/3.5.0/DropdownAlert.js#L472-L477) like this:

    <TouchableOpacity
        accessible={false}
        activeOpacity={!this.props.tapToCloseEnabled || showCancel ? 1 : 0.95}
        onPress={!this.props.tapToCloseEnabled ? null : () => this.close('tap')}
        disabled={!this.props.tapToCloseEnabled}
        onLayout={event => this.onLayoutEvent(event)}
    >

This seems reasonable since it is unlikely that you want to make the entire alert one single accessible zone unless you decide to not use any cancel button.

Additionally, you could have an additional properly that allows this to be turned on/off or a more comprehensive accessibility solution. But, baby steps...

### Additional Information

* React Native version: 0.55.3
* react-native-dropdownalert version: 3.5.0
* Platform(s) (iOS, Android, or both?): iOS
* iOS version: 11.4.1
* Android version: n/a

**Comment by testshallpass** [comment]
**Acceptance criteria**
* Expose accessible as prop.
* Document it on README.

**Comment by testshallpass** [comment]
Added version 3.8.0

**Comment by ryanhomer** [comment]
Thanks @testshallpass. That's exactly what I needed. It works on Android. I don't think you'll need to worry about configuration at this level. Accessibility can be configured in the `renderMessage` and `renderCancel` components.
