### ISSUE TITLE
(in)activeStatusBarStyle only applies to iOS

### ISSUE THREAD

**Issue by ryanhomer** [testshallpass/react-native-dropdownalert#140]
#### Short Description

When using the `activeStatusBarStyle` or `inactiveStatusBarStyle` props, it only applies to iOS.

#### Steps to Reproduce / Code Snippets / Usage

    <DropdownAlert
        activeStatusBarStyle="dark-content"  /* this won't work on Android */
        inactiveStatusBarStyle="light-content"   /* this won't work on Android */
        inactiveStatusBarBackgroundColor="#FFFFFF24"
    />

#### Expected Results

It should apply to both iOS and Android since `statusBarStyle` is a valid property of `StatusBar` on Android too.

Looking at the source code, I see code blocks like this:

    if (IS_ANDROID) {
      StatusBar.setBackgroundColor(activeStatusBarBackgroundColor, true);
      StatusBar.setTranslucent(translucent);
    } else if (IS_IOS) {
      StatusBar.setBarStyle(activeStatusBarStyle, true);
    }

that should be like this:

    if (IS_ANDROID) {
      StatusBar.setBackgroundColor(activeStatusBarBackgroundColor, true);
      StatusBar.setTranslucent(translucent);
    }
    StatusBar.setBarStyle(activeStatusBarStyle, true);

Any reason to _not_ do it like this?

### Additional Information

* React Native version: 0.55.3
* react-native-dropdownalert version: 3.5.0
* Platform(s) (iOS, Android, or both?): Android
* iOS version: n/a
* Android version: 6

**Comment by testshallpass** [comment]
@ryanhomer Thanks, that will do it. I was unaware `setBarStyle` was available for Android.

**Comment by testshallpass** [comment]
@ryanhomer I added the change to PR #146. Please review.

**Comment by testshallpass** [comment]
@ryanhomer Merged PR. Try out v3.7.0
