### ISSUE TITLE
Android Broken with Debug JS Remotely

### ISSUE THREAD

**Issue by robotrory** [testshallpass/react-native-dropdownalert#141]
#### Short Description

When debugging JS remotely, only the status bar on Android changes colour. No dropdown appears, and the status bar colour never reverts to the prior state. This doesn't occur on iOS.

#### Steps to Reproduce / Code Snippets / Usage

Run example app with "Debug JS Remotely" turned on.

#### Expected Results

The app shows a dropdown.

### Additional Information

* React Native version: 0.56.0 (example uses 0.54.4)
* react-native-dropdownalert version: 3.5.0 (example uses 3.2.0)
* Platform(s) (iOS, Android, or both?): Android
* Android version: 6.0.1
* Example:

<img src="https://user-images.githubusercontent.com/1873019/45545557-8aa82e80-b812-11e8-84b0-f0dc1f52b885.gif" width="300" />

**Comment by testshallpass** [comment]
@robotrory Hi, I recently updated the example. Please retry. Also, see if it's related issue #133. Thanks.

**Comment by testshallpass** [comment]
Closing as stale
