### ISSUE TITLE
Modal Covers the notification

### ISSUE THREAD

**Issue by sahanatroam** [testshallpass/react-native-dropdownalert#144]
Hi team,
Followed all the instructions and this is still happenning

![simulator screen shot - iphone 5s - 2018-09-25 at 13 56 49](https://user-images.githubusercontent.com/29851224/45988403-ddaf9a80-c0ca-11e8-965b-073bc28f23cd.png)

**Comment by sahanatroam** [comment]
@testshallpass any thoughts on this ??

**Comment by testshallpass** [comment]
@sahanatroam The DropdownAlert should be inside the modal and invoke from there.

**Comment by sahanatroam** [comment]
Ahh.. I see.. that's one way to do it. Thank you

**Comment by testshallpass** [comment]
@sahanatroam Modals are higher in zIndex than any other component. Please reopen if you need further assistance.

**Comment by HugoGresse** [comment]
I understand this, but it make having a single DropdownAlert for the whole app difficult + time consuming :/ 
Is there no other solution for this?
