### ISSUE TITLE
Add image through alertWithType 

### ISSUE THREAD

**Issue by supperking03** [testshallpass/react-native-dropdownalert#161]
I want to pass image source through function alertWithType() to show user avatar when receive message from server.

**Comment by testshallpass** [comment]
A workaround could be state changing on image source props.

**Comment by testshallpass** [comment]
**Acceptance criteria**

- image source parameter can be local or remote (number or string)
- if provided overrides any image source props
- inherits image style props
- returns it in alertData

**Comment by testshallpass** [comment]
It also in the works see: #175
