### ISSUE TITLE
Use TimerMixin and this.setTimeout instead setTimeout

### ISSUE THREAD

**Issue by Zaporozhec7** [testshallpass/react-native-dropdownalert#162]
#### Short Description

`setTimeout` call callback with wrong timeout when debug remotely. 
Also `setTimeout` usage can lead to possible fatals and not recommended to use in react native components.

#### Steps to Reproduce / Code Snippets / Usage

Run App on real device with enabled "Debug JS Remotely" and show alert with some small "closeInterval", like 500 - 2000, and can see that alert closed with noticeably longer time than specified.

#### Expected Results

Alert close with "closeInterval" as specified, regardless of "Debug JS Remotely"

### Additional Information

Related issue: https://github.com/facebook/react-native/issues/4470
About TimerMixin: https://facebook.github.io/react-native/docs/timers.html#timermixin

I have modified library code locally (temporary), to add `console.log()` statements like that:

 ```
 if (closeInterval > 1) {
        if (this._closeTimeoutId != null) {
          clearTimeout(this._closeTimeoutId);
        }
        console.log(closeInterval);
        this._closeTimeoutId = setTimeout(
          function() {
            this.close('automatic');
            console.log('close called');
          }.bind(this),
          closeInterval
        );
      }
``` 
And noticed that function called with noticeably longer time than closeInterval value

* React Native version: 0.57.7
* react-native-dropdownalert version: 3.8.0
* Platform(s) (iOS, Android, or both?): Android
* Android version: 5.1 (physical device)

P.s.: Thank you very much for this library and your work

**Comment by testshallpass** [comment]
@Zaporozhec7 I appreciate you bringing this to my attention. I like that TimerMixin handles the clean up and easy to adopt. I am highly considering it. Some of the documentation and related issue you linked seems dated a bit, do you know if it is still an issue?

**Comment by Zaporozhec7** [comment]
@testshallpass I don't know is it still issue in debug mode, because I was not work with it last 2 months

**Comment by testshallpass** [comment]
@Zaporozhec7 I see, I am actually asking in general. But, I'll retest and go from there. Thanks.

**Comment by testshallpass** [comment]
I centralized the timeout usage and ensure it's cleared in the refactor task. #197

**Comment by testshallpass** [comment]
TimerMixins as been archived: https://github.com/reactjs/react-timer-mixin
