### ISSUE TITLE
StatusBarColor doesn't go back to its original color while typing in TextInput

### ISSUE THREAD

**Issue by Albert0405** [testshallpass/react-native-dropdownalert#164]
Here's my code, it's working perfectly fine, after the DropdownAlert (for example "error" which changes the statusBarBackgroundColor to red) have been shown to the screen, it changes the StatusBarBackgroundColor to its original color of "#2699fb" which is good and what i am expecting to happen but i notice while im typing something in one of my TextInput, it didnt change the StatusBarBackgroundColor to "#2699fb" and remain the color to what ever type of Alert for example "error" which is red, "warn" which is orange, "info" which is blue and so on.......

```
<DropdownAlert
  ref={ref => (this.dropdown = ref)}
  inactiveStatusBarBackgroundColor="#2699FB"
/>
```

**Comment by testshallpass** [comment]
@Albert0405 "while im typing something in one of my TextInput, it didnt change the StatusBarBackgroundColor" I want to clarify this or add steps to reproduce, are you invoking the alert as you type something?

**Comment by Albert0405** [comment]
Im using your DropdownAlert in one of form, let say in Authentication Form. If the user typed nothing in the form then he/she tapped the login button, the DropdownAlert will be open in the screen for example withAlertType of warn and then i suddenly tried to type on the TextInput while the DropdownAlert is still open in the top of the app. When the DropdownAlert was closed after like 4seconds while me typing on my TextInput, it didnt turn the statusBarBackgroundColor to its original color, it changes to orange which is the color of warn im using.

Also i notice while the DropdownAlert is open and you suddenly tried to go back to your previous navigation, it also didnt turn the statusBarBackgroundColor to its original color

**Comment by Albert0405** [comment]
### **While typing in TextInput the color remained orange**
![ezgif-2-40f6d262359b](https://user-images.githubusercontent.com/38030623/50570093-62482f80-0d30-11e9-8026-a9ee9aa740b8.gif)


### **While DropdownAlert is open, i tried to tap on my device BackButton and this happens**
![ezgif-2-b3725f5a0f5c](https://user-images.githubusercontent.com/38030623/50570095-65dbb680-0d30-11e9-9b84-19563a63790b.gif)

**Comment by testshallpass** [comment]
Possibly related to #169. I need to retest.

**Comment by testshallpass** [comment]
I was **unable** to reproduce using:
* Android emulator: Pixel API 26 
* react-native-dropdownalert: v3.10.0
* react-native: v0.55.4
