### ISSUE TITLE
Title Padding Error

### ISSUE THREAD

**Issue by Sagaryalioe** [testshallpass/react-native-dropdownalert#168]
#### Short Description

The Error title is overlapped with status bar.

![screenshot_20190101-140916](https://user-images.githubusercontent.com/20223667/50571455-801aa080-0dd3-11e9-9c08-2c52dce80cce.png)

#### Steps to Reproduce / Code Snippets / Usage

> Similar to this

```
import DropdownAlert from 'react-native-dropdownalert';
export default class App extends Component {
  componentDidMount() {
    this.fetchData();
  }
  fetchData = async () => {
    try {
      await fetch('https://mywebsite.com/endpoint/');
    } catch (error) {
      this.dropdown.alertWithType('error', 'Error', error.message);
    }
  };
  render() {
    return (
      <View>
         // !!! Make sure it is the last component in your document tree.
        <DropdownAlert ref={ref => this.dropdown = ref} />
      </View>
    );
  }
}
```

#### Expected Results
[Like this](https://camo.githubusercontent.com/2a5dcd1d344b51d58ac8a1c7294b4e9dcb0d8ed9/68747470733a2f2f7261772e6769746875622e636f6d2f746573747368616c6c706173732f72656163742d6e61746976652d64726f70646f776e616c6572742f6d61737465722f73637265656e73686f74732f64656d6f2e676966)

### Additional Information

* React Native version: 0.55.4
* react-native-dropdownalert version: 3.9.0
* Platform(s) (iOS, Android, or both?): Android
* iOS version: [FILL THIS OUT]
* Android version: [FILL THIS OUT]

**Comment by testshallpass** [comment]
@Sagaryalioe The root cause is app's `StatusBar` translucent property is set to `true` which in turn  is showing as expected. translucent definition:
> If the status bar is translucent. When translucent is set to true, the app will draw under the status bar. This is useful when using a semi transparent status bar color.
* http://facebook.github.io/react-native/docs/statusbar#translucent

**Comment by tompap** [comment]
Adding translucent props to True, make it props nearly properly

<DropdownAlert translucent /> 

The statusbar background is not the same color as the dropdown (due to opacity) but It's more more better no text overlaps
