### ISSUE TITLE
SafeAreaView and onLayoutEvent being called repeatitively

### ISSUE THREAD

**Issue by kevinvuillemin** [testshallpass/react-native-dropdownalert#173]
#### Short Description

Here's my code:

`
<DropdownAlert errorColor={Colors.niceRed} infoColor={Colors.niceBlue} showCancel={false} containerStyle={{paddingHorizontal:50}} useNativeDriver={false} startDelta={WINDOW.height + 230} endDelta={WINDOW.height + 20} closeInterval={8000} onClose={data => this._onCloseDropDown(data)}  ref={ref => DropDownHolder.setDropDown(ref)} />
`

It does not work on iphone X, once the dropdown is displayed, my application is blocked. But working when i delete props startDelta and endDelata. Do you know why ?

**Comment by testshallpass** [comment]
@kevinvuillemin I investigated a bit and right now it appears `onLayout` being called infinitely and the component rendering again and again as the deltas are overridden. I need to dig a little deeper to understand root cause.

**Comment by testshallpass** [comment]
I was able to isolate to iPhone X and `SafeAreaView`. However, your startDelta and endDelta values would render DropDownAlert off screen. It is saved by logic in `onLayoutEvent`. And so after I made `SafeAreaView` a `View` it would not call `onLayoutEvent` repetitively be back to normal.

**Comment by testshallpass** [comment]
I refactored `onLayoutEvent` and it prevents repetitive unnecessary state changes. #197
