### ISSUE TITLE
Can't display DropdownAlert.

### ISSUE THREAD

**Issue by dev-ns8** [testshallpass/react-native-dropdownalert#174]
#### Short Description

I have two different errors happening, when I don't try to use any JS logic code to display the Alert and simply put it into the component tree manually as such: 
`          <DropdownAlert
              visible={true}
              type={'error'}
              title={'Error'}
              message={'Something went wrong.'} />`
I get the error: 

> Adjacent JSX elements must be wrapped in an enclosing tag

My component tree has all enclosing tags just fine and this error only boils up when I insert a DropdownAlert component

secondly if I put logic into my constructor such as:

`     this.dropdown.alertWithType(
       'test',
         'test me',
         'fucking test me bitch'
     );`

I get an error of

> undefined is not an object (evaluating '_this.dropdown.alertWithType')

#### Expected Results

A drop down appearing with no errors

### Additional Information

* React Native version: 0.55.4
* react-native-dropdownalert version: 3.9.1
* Platform(s) (iOS, Android, or both?): iOS

**Comment by testshallpass** [comment]
For those who reference this issue, the `ref={ref => this.dropdown = ref}` was left out which caused the `undefined`
