### ISSUE TITLE
Add custom data to the onClose callback

### ISSUE THREAD

**Issue by rdewolff** [testshallpass/react-native-dropdownalert#177]
Hello!

Is there a way to pass some custom data to the payload returned by the `onClose` callback?

Ideally, I wish to be able to do the following :

```js
// call my alert with custom data
myDropdown.alertWithType(type, title, message, {navigateTo: 'myPage'})
```

and in my `onClose` handler, I would have something like : 
```js
const onClose = (data) => {
  // if the user clicked on the action, we process it
  if (data.action === 'tap') {
    // process the action from the notification
    myNavigationHandler.navigateTo(data.payload.navigateTo)
  }
}
```

What do you think? Is there a way to do this today? Would a PR in that direction make sense?

Cheers

**Comment by rdewolff** [comment]
PS: yes, I know we can read the title and the message form the `data` payload, but in a i18n app, that's not elegant to do so.

**Comment by testshallpass** [comment]
@rdewolff So you want DropdownAlert to be the middle man in an data exchange so to speak, right?

**Comment by rdewolff** [comment]
Well when you throw many alerts, you want to have a parameter to be able to react to it. So adding a `payload` would allow that. 
Imagine you have 2 alerts at the same time, you want to react differently when the user push on each notification. With a parameter like this payload, this can be done.

**Comment by rdewolff** [comment]
Cf comment https://github.com/testshallpass/react-native-dropdownalert/pull/178#issuecomment-464278687 :)
