### ISSUE TITLE
Warning after parent node unmounted.

### ISSUE THREAD

**Issue by ChiuMungZitAlexander** [testshallpass/react-native-dropdownalert#179]
#### Short Description

Warning after parent node Modal closed.

#### Steps to Reproduce / Code Snippets / Usage

```
<Modal
  visible={modalVisible}
  animationType="slide"
  onRequestClose={() => this.onRequestClose()}
>
  <DropdownAlert ref={(el) => { this.Alert = el; }} />
  // other code
</Modal>
```

I used react-native-dropdownalert in the way above. However, I met a problem unexpectedly. 

This is, if I press back button (or back icon) when the notification has not gone, the phone throws warning of `can't call setState on an unmounted component`.

I believe it is because parent node, in my case it is Modal, has unmounted while the time interval has not gone off. So when time is up, dropdownalert cannot call setState.

And I just tried to press back button after the dropdownalert disappears. Yes, no warnings.

I've notice there are some changed in #85, but I have no ideas why it is still not working.

#### Expected Results

Unmounting parent node will not trigger warning before dropdownalert dismisses.

### Additional Information

* React Native version: 0.57.1
* react-native-dropdownalert version: 3.8.1
* Platform(s) (iOS, Android, or both?): Android, IOS not known
* iOS version: N/A
* Android version: Androind 7.0

**Comment by oliemansm** [comment]
I'm having the same problem.

**Comment by testshallpass** [comment]
I have noticed this myself. Even though, #85 tried to address it by clearing the timeout you can see that state is still changed in the `closeDirectly` function.

**Comment by testshallpass** [comment]
Possibly could be helped by incorporating TimerMixin: #162

**Comment by testshallpass** [comment]
@ChiuMungZitAlexander or @oliemansm Please retest with `4.0.0`. Thanks.

**Comment by testshallpass** [comment]
I was unable to reproduce on `4.1.1` on react-native `0.59.10`. However, I rechecked logic and the time out is cleared on `componentWillUnMount` which prevents state change after the fact.
