### ISSUE TITLE
iOS 9 wrong dropdown height

### ISSUE THREAD

**Issue by kirillpisarev** [testshallpass/react-native-dropdownalert#181]
#### Short Description

On iOS 9 initial dropdown height is too big and it raises on each dropdown appearance.

#### Steps to Reproduce / Code Snippets / Usage

![dropdown](https://user-images.githubusercontent.com/1886908/53171431-b9ada200-35f3-11e9-9974-a1e02de5a9a5.gif)

### Additional Information

* React Native version: 0.58.4
* react-native-dropdownalert version: 3.9.2
* Platform(s) (iOS, Android, or both?): iOS
* iOS version: 9

**Comment by kirillpisarev** [comment]
Like it is said in docs: The purpose of SafeAreaView is to render content within the safe area boundaries of a device. It is currently only applicable to iOS devices with iOS version 11 or later.

So i have changed SafeAreaView to a simple View component for old versions and seems like it is working just fine now.

**Comment by testshallpass** [comment]
I am onboard with the fix. I reviewed the changes and had some feedback, please take a look. @kirillpisarev 

Also, I found out `SafeAreaView` does not play nice with custom deltas #173

**Comment by kirillpisarev** [comment]
Your changes now the part of the PR.

**Comment by testshallpass** [comment]
Merged fix in v3.11.0
