### ISSUE TITLE
doc modification suggestion

### ISSUE THREAD

**Issue by articolo** [testshallpass/react-native-dropdownalert#188]
I strongly recommend to add this repo as an example https://github.com/mitsuruog/react-native-dropdownalert-router-sample. The architecture he use to pass instance of the `ref` is solved me SO MANY PROBLEMS.

**Comment by kirillpisarev** [comment]
But he uses an approach for storing dropdown ref that is illustrated within the example from the docs: https://github.com/testshallpass/react-native-dropdownalert#caveats (example #2).

**Comment by testshallpass** [comment]
I added to README, thanks @articolo
