### ISSUE TITLE
Pass children as a custom component

### ISSUE THREAD

**Issue by sibelius** [testshallpass/react-native-dropdownalert#19]
Tks for this great component!

I wanna pass a custom children to be rendered by the dropdownalert, like this option here: https://github.com/react-native-component/react-native-smart-toast

I think instead of having three parameters like `type, title, and body`, you should accept an object that could contain many options, making easily to add more properties

I'm using this component to show an notification inside my app, and each notification needs to be customizable, and it should also do different actions when u click on the notification itself. I would like to pass a custom function for `onClose` event for each time I've call `dropdown.alert`

**Comment by devbriguy** [comment]
For ```onClose``` you could do a state change although that is a bit messy. I agree with you that an object would allow more scalability. 

Would you say you need more style changes for let's say each notification? And show/hide different elements?

You could potentially spawn more in render and ref them as such: ```this.dropdown1 ... this.dropdown2```

**Comment by sibelius** [comment]
It is not only about style, I would like to provide a more complex component inside dropdown, for instance, an alert with two button, or an image that go to another scene of my app when the user clicked on it

**Comment by devBrian** [comment]
So something like:

 ```javascript
<DropdownAlert {...props}>
  <Text /> 
  <Image />
  <Icon />
// ... etc
</DropDownAlert>

/// OR
// something out of the Gifted Chat module

<DropDownAlert renderText={this.renderText} /> // ... etc

**Comment by sibelius** [comment]
https://github.com/react-native-component/react-native-smart-toast allows us to pass when calling the alert from the ref.

It would be this._dropdown.show({children: <Image />, ...})

**Comment by devBrian** [comment]
That's pretty cool and the usage is quite contained. It definitely reduces the amount of props that I have been thinking on reducing / making as simple as possible. I'll play around with this. Thanks for the suggestion.

**Comment by devBrian** [comment]
Hi @sibelius. Sorry for the delay on this. I have been super busy on end of year projects. Perhaps Halloween candy will get this going. :)

**Comment by sibelius** [comment]
do not worry about it, I've moved to https://github.com/exponentjs/ex-navigation that includes Alert Bars

they do not handle custom alert bar as well, but it is good enough for now (https://github.com/exponentjs/ex-navigation/blob/master/src/ExNavigationAlertBar.js)

**Comment by devBrian** [comment]
So as you said something like this I envision:
```javascript
var children = {
  icon: (
    <Image style={{width: 40, height: 40}} source={{uri: 'https://facebook.github.io/react/img/logo_og.png'}} />
  ),
  title: (
    <Text style={{fontSize: 20}} numberOfLines={1}>{'Info'}</Text>
  ),
  message: (
    <Text style={{fontSize: 20}} numberOfLines={3}>{'System is going down at 12 AM tonight for routine maintenance. We\'ll notify you when the system is back online.'}</Text>
  ),
  cancelButton: (
    <TouchableHighlight style={{width: 40, height: 40}} onPress={() => {console.log('onCancel')}} underlayColor={'red'}>
      <Image style={{width: 40, height: 40}} source={{uri: 'https://facebook.github.io/react/img/logo_og.png'}} />
    </TouchableHighlight>
  )
}
this.dropdown.alertWithData('Info', children, this.dropdown.defaultContainer, (data) => {
  // ... do something
})
```

**Comment by sibelius** [comment]
U could have children as just a component, children = <MyCustomAlert />. So the user can do whatever he wants

**Comment by Jacse** [comment]
I think an API along these lines would be great:
````
const myComponent = (
    <View>
        <Text>Custom component with images, multiple buttons etc.</Text>
    </View>
);
this.dropdown.alertComponent(myComponent, customOnCloseCallback)
````

Now that I think about it,  a function returning a component might actually be better:
````
const myComponent = (
    <View>
        <Text>Custom component with images, multiple buttons etc.</Text>
    </View>
);
this.dropdown.alertComponent((stuffFromDropDown) => myComponent, customOnCloseCallback)
````

I have a complex app and unfortunately had to move away from DropDownAlert, because I need to set custom onClose handlers on different alerts.

**Comment by Jonovono** [comment]
Is this feature still in the works?

**Comment by testshallpass** [comment]
Closing as stale but could be resurrected
