### ISSUE TITLE
react-native-dropdownalert with Redux

### ISSUE THREAD

**Issue by whittlem** [testshallpass/react-native-dropdownalert#191]
#### Short Description

Is it possible to store the ref in Redux so it is available to all child components within the app?

#### Steps to Reproduce / Code Snippets / Usage

Ideally something like this in the parent component:
(ref) => this.props.setDropdownAlertRef(ref)

And then this in the child components:
this.props.dropdownAlertReducer.ref.alertWithType('error', 'Error', error.message);

#### Expected Results

As above.

### Additional Information

* React Native version: 0.57.7
* react-native-dropdownalert version: 3.10.0
* Platform(s) (iOS, Android, or both?): IOS
* iOS version: latest

**Comment by mahyali** [comment]
Tried that. You can't store refs in redux state. What you can do is make a "Service" file

`
let dropDownAlert;

function setDropDownAlert(ref) {
  dropDownAlert = ref;
}

function alert(type: string, title: string, message: string) {
  dropDownAlert.alertWithType(type, title, message);
}

export default {
  dropDownAlert,
  alert,
  setDropDownAlert,
}
`

then in the very first rendered screen of your app

`
<DropdownAlert
          ref={ref => DropDownService.setDropDownAlert(ref)} />
`

Then anywhere you want to use a dropdown just import DropDownService and call the alert function.

**Comment by whittlem** [comment]
Oh I see. That makes sense. Thanks for the quick response. I will try that.

**Comment by whittlem** [comment]
@mahyali, this worked exactly has you said. Thanks very much.
