### ISSUE TITLE
Status bar change after close in ios

### ISSUE THREAD

**Issue by b3hz4d** [testshallpass/react-native-dropdownalert#193]
#### Short Description

Status bar style changed

#### Steps to Reproduce

After showing alert when alert closed the status bar style is changed on iOS

#### Expected Results

Statusbar style stay light content

### Additional Information

* React Native version: 0.58.6
* react-native-dropdownalert version: 3.9.1
* Platform(s) (iOS, Android, or both?): iOS
* iOS version: 12.2

**Comment by testshallpass** [comment]
@b3hz4d Yes, please set DropdownAlert prop `inactiveStatusBarStyle` to `light-content`

**Comment by dalmarcogd** [comment]
@b3hz4d You can change use property `updateStatusBa={false}`, this preserve your styled
`<DropdownAlert  elevation={3} showCancel={true} updateStatusBar={false} ref={ref => this.dropdown = ref} closeInterval={6000} />`
