### ISSUE TITLE
Show cancel Button Image in just success or warn alert type 

### ISSUE THREAD

**Issue by babar7** [testshallpass/react-native-dropdownalert#194]
I want to show cancel button in some cases of alert type not every time when message shows

**Comment by testshallpass** [comment]
A workaround could be changing the `showCancel` prop on a state change like when it's warn or success types.

**Comment by testshallpass** [comment]
I am satisfied with the workaround and I welcome any PR to address this. I suggest by sending a flag in the payload in `alertWithType` similar to how image source was overridden.

**Comment by testshallpass** [comment]
Closing as per comments above.
