### ISSUE TITLE
defaultContainer.paddingTop is not working on android

### ISSUE THREAD

**Issue by sabaturgay** [testshallpass/react-native-dropdownalert#196]
#### Short Description

In Android, defaultContainer.paddingTop not working correctly. For fixing I added  defaultContainer={{ paddingTop: Platform.OS === 'android' ? 20 : 0 }}. This can be fixed in component. 

### Additional Information

* React Native version: expo sdk:32
* react-native-dropdownalert version: 3.11.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by testshallpass** [comment]
Hi @sabaturgay please retest with `4.0.0`. Thanks.

**Comment by sabaturgay** [comment]
> Hi @sabaturgay please retest with `4.0.0`. Thanks.
Thank you for your reply and sorry for my late answer. But the issue is not fixed.

**Comment by testshallpass** [comment]
@sabaturgay Please provide your Actual (how it's broken) and Expected (how it should work). I retested and applied the `defaultContainer` prop with `paddingTop: 20` works as expected on iOS and Android.

**Comment by testshallpass** [comment]
Closing as stale.
