### ISSUE TITLE
Alerts unexpectedly autoclosing after update to latest release

### ISSUE THREAD

**Issue by projectpublius** [testshallpass/react-native-dropdownalert#202]
#### Short Description

Similar to #108, updating to the latest version from `3.11.0` results in alerts autoclosing on iOS and Android when `closeInterval={0}`.

#### Steps to Reproduce / Code Snippets / Usage

```
        <DropdownAlert
          closeInterval={0}
          ref={ref => DropDownHolder.setDropDown(ref)}
        />
```

#### Expected Results

Alert should stay open until dismissed by user.  Downgrading to `3.11.0` fixes the issue.

### Additional Information

* React Native version: `0.59.9`
* react-native-dropdownalert version: `4.0.1`
* Platform(s) (iOS, Android, or both?): `Both`
* iOS version: `12.3.1`
* Android version: `9`

**Comment by testshallpass** [comment]
@projectpublius Technically, it is working as expected but definitely is not good if there are use cases for preventing it from automatically closing by setting `closeInterval` to 0. And so I was able to track it down, apparently, before v4.0.0 there was a condition:`if (closeInterval > 1) {` that would prevent it from automatic close.

**Comment by testshallpass** [comment]
@projectpublius Please review PR #203 and 👍 Thanks.
