### ISSUE TITLE
[react-native-web] Cannot assign to read only property

### ISSUE THREAD

**Issue by sabaturgay** [testshallpass/react-native-dropdownalert#204]
#### Short Description
Hi,
When I used the component with react-native-web. There is an error like ' Cannot assign to read only property 'exports' of object '#<Object>'. Then I just changed your export type like module.exports  to export const in constant.js file. I tried it worked. If you can change this in the repo , it will be nice.
Thank you for your time.

### Additional Information

* React Native version: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz
* react-native-dropdownalert version: 4.0.2
* Platform(s) (iOS, Android, or both?): Web

**Comment by testshallpass** [comment]
Okay I will adopt `export` as defined: https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export similar to what you said.

**Comment by sabaturgay** [comment]
> Okay I will adopt `export` as defined: https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export similar to what you said.

Thank you. I will try it as soon as possible.
