### ISSUE TITLE
DropdownAlert is not shown when using ScrollView

### ISSUE THREAD

**Issue by hossamnasser938** [testshallpass/react-native-dropdownalert#205]
#### Short Description
DropdownAlert works fine with me in screens with a fixed size. On using scrollview, if the user is at the top, DropdownAlert still works fine. The problem appears when the user is scrolled down. In this case only the status bar reflects that there is an alert by changing its color but the alert itself is not shown.

#### Steps to Reproduce / Code Snippets / Usage
```js
import React, { PureComponent } from 'react';
import { Text, ScrollView, TouchableOpacity } from 'react-native';
import Dropdownalert from 'react-native-dropdownalert';

export default class HomeScreen extends PureComponent {
    render() {
        const numbers = [];
        for ( let i = 0; i < 100; i++ ) {
            numbers.push( i );
        }

        const listItems = numbers.map( item => { 
                return(
                    <TouchableOpacity 
                      onPress = { () => this.dropDownAlert.alertWithType( 'success', 'Success', 'Test' ) }
                    > 
                        <Text>number { item }</Text> 
                    </TouchableOpacity> 
                );
            } 
        );

        return(
            <ScrollView>
                { listItems }
                <Dropdownalert 
                  ref = { ref => this.dropDownAlert = ref }
                />
            </ScrollView>
        );
    }
}
```

#### Expected Results
The DropdownAlert should appear.

### Additional Information
I tried to put the DropdownAlert as the first child to the ScrollView but the same problem exists.

* React Native version: 0.59.8
* react-native-dropdownalert version: ^4.0.1
* Platform(s) (iOS, Android, or both?): Android
* Android version: 28.0.3

**Comment by ngandhy** [comment]
I'm seeing this issue as well. Anyone have any luck figuring this out?

**Comment by ngandhy** [comment]
react-native-dropdownalert and react-native-splash-screen seem to be incompatible. That's what it turned out for me.

**Comment by testshallpass** [comment]
I was able to reproduce. The fix or workaround is to wrap `ScrollView` in a `View` and put `DropdownAlert` as last component outside the `ScrollView` like below:

```javascript
// ...
    return (
      <View>
        <ScrollView>
          {listItems}
        </ScrollView>
        <DropdownAlert ref={ref => this.dropDownAlert = ref} />
      </View>
    );
// ...
```
@ngandhy Please create separate issue on that. Thanks.

**Comment by hossamnasser938** [comment]
Thanks for your help. I'll test your solution when I have the opportunity @testshallpass
