### ISSUE TITLE
Globally accessing dropDownAlert ref

### ISSUE THREAD

**Issue by parthv21** [testshallpass/react-native-dropdownalert#206]
#### Short Description
I want to use this component globally from all my other components. So I decided to define it within my App component and set its ref to a global variable which I exported. But I could not access it from the other components, where it shows as undefined.

#### Steps to Reproduce / Code Snippets / Usage

```
export let dropDownAlertRef: DropdownAlert;

export default class App extends React.Component<any, any> {
  render() {
    return (
      <Provider store={store}>
        <DropdownAlert
          ref={(ref) => {
            dropDownAlertRef = ref as DropdownAlert;
          }}
        />
        <Navigator />
      </Provider>
    );
  }
}
```

#### Expected Results

Access the exported ref from other files so I can directly call the alert showing function.

### Additional Information

* React Native version: 0.59.8
* react-native-dropdownalert version: 4.1.0
* Platform(s) (iOS, Android, or both?): both
* iOS version: 12
* Android version: 6

**Comment by ardyfeb** [comment]
the readme already have an example https://gist.github.com/testshallpass/6c6c867269348c485a1e0d6ae3f55e90

**Comment by testshallpass** [comment]
Yes, checkout [Caveats](https://github.com/testshallpass/react-native-dropdownalert#caveats) section for examples.
