### ISSUE TITLE
Using redux with dropdown

### ISSUE THREAD

**Issue by tiagocorreiaitcenter** [testshallpass/react-native-dropdownalert#211]
After searching around the documentation and issues related to the topic I came around a "solution" to use the redux store, on the code below I have a reducer that stores the current alert, when the store changes I set dropdown alert to the store state, this works all well until the point where I have onclose and onCancel actions, on those im cleaning the store, so if for example I have Alert A open and I click close and on the same exact moment a new alert was set on the state, it will close the old and new alert at the same time since the element is the same.
So I was wondering if there is some example of a similar behavior working with redux or any other way of handling this situation?

```javascript
import React, { useEffect, useRef, Fragment } from 'react';
import DropdownAlert from 'react-native-dropdownalert';
import { useSelector, useDispatch } from 'react-redux';

import { alerts as alertsConfig } from 'Base/config.json';
import { cleanAlert } from 'Api/store/actions';

const alertsTimeout = alertsConfig.timeout || 8000;

const DropdownAlertWrapper = () => {
  const alert = useSelector((state) => state.dropDownAlert);

  const dispatch = useDispatch();
  let dropdownalertRef = useRef(null);

  useEffect(() => {
    if (Object.keys(alert).length > 0) {
      dropdownalertRef.alertWithType(alert.type, alert.title, alert.message);
    }
  }, [alert]);

  return (
    <Fragment>
      <DropdownAlert
        updateStatusBar={false}
        showCancel={alert.closable}
        tapToCloseEnabled={alert.closable}
        replaceEnabled={false}
        closeInterval={alert.timesout ? alertsTimeout : 0}
        onClose={() => dispatch(cleanAlert())}
        onCancel={() => dispatch(cleanAlert())}
        ref={(ref) => (dropdownalertRef = ref)}
      />
    </Fragment>
  );
};

export default DropdownAlertWrapper;

```

Im using the following versions:
    "react": "16.8.6"
    "react-native": "0.60.4"
    "react-native-dropdownalert": "^4.1.1"

**Comment by tiagocorreiaitcenter** [comment]
Ended up figuring it out myself.

**Comment by testshallpass** [comment]
@tiagocorreiaitcenter Do you mind sharing for others that may have similar issue? I also am interested and willing to add it to the caveats section in the Readme.

**Comment by tiagocorreiaitcenter** [comment]
@testshallpass the solution above pretty much works, I ended up figuring out that the issue is like having 3 alerts coming at the same time, one overlaps the other because the package itself only supports one alert at time so must of the times I would only see the last message. A good improvement would be to support multiple alerts one below other in my opinion, other than that great work you have here
