### ISSUE TITLE
Constant exports is breaking react-native-web

### ISSUE THREAD

**Issue by BillyFigueroa** [testshallpass/react-native-dropdownalert#213]
#### Short Description

Constants being exporter in `constants.js` causing react-native-web to break

Errors...

![Screen Shot 2019-09-11 at 11 16 43 PM](https://user-images.githubusercontent.com/1371105/64751506-51b89d80-d4ea-11e9-810b-e12fcee9a77d.png)

#### Steps to Reproduce / Code Snippets / Usage

Try to use DropdownAlert in a project with react-native-web

#### Expected Results

react-native-web projects should not crash

### Additional Information

* React Native version:  0.59.8
* react-native-dropdownalert version: ^4.1.1
* Platform(s) (iOS, Android, or both?): react-native-web
* iOS version: N/A
* Android version: N/A
* React Native Web version: ^1.0.0-alpha.9

### Solution
Change the constants.js from....

```javascript
module.exports = {
  DEFAULT_IMAGE_DIMENSIONS,
  WINDOW,
  HEIGHT,
  WIDTH,
  IS_IOS,
  IS_ANDROID,
  IS_IOS_BELOW_11,
  TYPE,
  ACTION,
  getDefaultStatusBarStyle,
  getDefaultStatusBarBackgroundColor,
};
```

to this

```javascript
export {
  DEFAULT_IMAGE_DIMENSIONS,
  WINDOW,
  HEIGHT,
  WIDTH,
  IS_IOS,
  IS_ANDROID,
  IS_IOS_BELOW_11,
  TYPE,
  ACTION,
  getDefaultStatusBarStyle,
  getDefaultStatusBarBackgroundColor,
};
```

fixes the issue

**Comment by testshallpass** [comment]
@BillyFigueroa This relates to #204 which has been fixed in `4.2.0`.
