### ISSUE TITLE
Unable to change the backgroundColor

### ISSUE THREAD

**Issue by Zilleabbas10** [testshallpass/react-native-dropdownalert#216]
#### Short Description
I am trying to provide custom style to match my theme, but the Alert will not change the backgroundColor.

#### Steps to Reproduce / Code Snippets / Usage
1. change color by the successColor prop
OR
2. provide defaultContainer={{backgroundColor: 'white'}}
OR
3. provide wrapperStyle ={{backgroundColor: 'white'}}

is throws TS error contentContainerStyle={{backgroundColor: Colors.white}}

#### Expected Results
background of the notification should turn white
### Additional Information

* React Native version: 0.60.5
* react-native-dropdownalert version: latest
* Platform(s) (iOS, Android, or both?): both
* iOS version: 13
* Android version: 28

**Comment by matapo** [comment]
@Zilleabbas10 I have implemented using following:

<DropdownAlert
            successColor={Colors.primary} <-- here you can specify the background color
            renderImage={() => {}} // no icon
            titleNumOfLines={0}
            defaultContainer={{
              padding: 8,
              paddingTop: StatusBar.currentHeight,
              flexDirection: "row"
            }}
            ref={ref => AlertHelper.setDropDown(ref)}
            onClose={() => AlertHelper.invokeOnClose()}
          />


<img width="305" alt="Screenshot 2019-12-13 at 10 12 52" src="https://user-images.githubusercontent.com/26110566/70788430-26677800-1d91-11ea-9cc6-6df15f85cb82.png">

**Comment by testshallpass** [comment]
I can change background color using props `successColor={'white'}` and `containerStyle={{backgroundColor: 'white'}}`. Keep in mind, using `successColor` implies you will invoke `success` alert type and using `containerStyle` implies you will invoke with empty or `custom` alert type. And thanks @matapo providing an example.
