### ISSUE TITLE
Dropdown Alert not appearing on iOS

### ISSUE THREAD

**Issue by HaseemUlHaq** [testshallpass/react-native-dropdownalert#219]
Working fine on Android but not showing any Alert in iOS

* React Native version: ^0.61.2
* react-native-dropdownalert version: ^4.2.0
* Platform(s) (iOS, Android, or both?): iOS
* iOS version: iPhone X 12.1

**Comment by HaseemUlHaq** [comment]
Closing, Found a way to display.

**Comment by blackwolf08** [comment]
@HaseemUlHaq how I am unable to do that

**Comment by HaseemUlHaq** [comment]
@blackwolf08 
Use DropdownAlert in App level, and place all other child components in View.
I added flex:1 in View and it worked.
`<View style={{ flex: 1 }}>
        <Other components />
        <DropdownAlert
          updateStatusBar={false}
          ref={(ref) => (this.dropDownAlertRef = ref)}
        />
 </View>`

**Comment by VTrngNghia** [comment]
> `updateStatusBar={false}`

This did not work for me

**Comment by VTrngNghia** [comment]
> @blackwolf08
> Use DropdownAlert in App level, and place all other child components in View.
> I added flex:1 in View and it worked.
> `<View style={{ flex: 1 }}>`
> ` <Other components />`
> ` <DropdownAlert`
> ` updateStatusBar={false}`
> ` ref={(ref) => (this.dropDownAlertRef = ref)}`
> ` />`
> `</View>`

This did not work for me
