### ISSUE TITLE
Any way to render alert below the header and not from the top of screen?

### ISSUE THREAD

**Issue by obiwankenoobi** [testshallpass/react-native-dropdownalert#220]
#### Short Description

I would like to make the alert to start render below a given header instead of from the top of the screen

Any way to achieve this?

**Comment by vikjovanov** [comment]
hey, 
check this demo: https://github.com/mitsuruog/react-native-dropdownalert-router-sample
I think is what you looking for

**Comment by obiwankenoobi** [comment]
@vikjovanov Yes! Thank you (:
