### ISSUE TITLE
DropdownAlert removing the StatusBar

### ISSUE THREAD

**Issue by HarshitMadhav** [testshallpass/react-native-dropdownalert#222]
#### Short Description

Hi! Firstly thanks for this awesome package.
I am stuck on an issue in which I am having a StatusBar component for my app and whenever I call this Dropdownalert to appear on the screen it removes the statusbar when the Dropdownalert disappears after some duration of time.

#### Steps to Reproduce / Code Snippets / Usage
In my App.js I am using it like this:
```
<SafeAreaView forceInset={{ top: 'always' }} style={{ flex: 1 }}>
        <StatusBar backgroundColor={'#c70b0b'}/>
         <DropdownAlert ref={ref => this.dropDownAlertRef = ref} />
      <AppNavigator/>
</SafeAreaView>
```

#### Expected Results

StatusBar should stay after the Dropdownalert disappears.

### Additional Information

* React Native version: 0.61.5
* react-native-dropdownalert version: 4.2.1
* Platform(s) (iOS, Android, or both?): Android
* iOS version: -
* Android version: Pie (9)

**Comment by appseugene** [comment]
same issue here on Android

**Comment by Dilgithub** [comment]
same issue here

**Comment by jorgnyg** [comment]
Try to set `inactiveStatusBarStyle="dark-content / light-content"` depending on your settings. Solved the problem for me.

**Comment by HarshitMadhav** [comment]
@jorgnyg Can you please share how and where are you using this line of code for the bug fix?

**Comment by jorgnyg** [comment]
@HarshitMadhav I'm using it here `<DropdownAlert inactiveStatusBarStyle="dark-content" ref={(ref) => DropDownHolder.setDropDown(ref)} />`

**Comment by testshallpass** [comment]
Please try out latest v4.3.0.

**Comment by matheushf** [comment]
light-content didn't work for me, on latest v4.3.0. I had to set the inactive and active manually to another color

**Comment by Joshmatjjen** [comment]
Solution to fix it

<DropdownAlert
              ref={(ref) =>
                setDropDown(ref)  
              inactiveStatusBarStyle={barStyle? light-content || ldark-content}
              inactiveStatusBarBackgroundColor={color? 'black'}
            />
Hope it helps?

**Comment by maksimpashchenko** [comment]
<DropdownAlert updateStatusBar={false} />

**Comment by maksimpashchenko** [comment]
To fix it 
<DropdownAlert updateStatusBar={false} />

**Comment by maksimpashchenko** [comment]
<DropdownAlert updateStatusBar={false} />

**Comment by maksimpashchenko** [comment]
To fix it 
`<DropdownAlert
              ref={(ref) =>
                setDropDown(ref)  
updateStatusBar={false}
            />`

**Comment by rwanito** [comment]
Hi !
It works for me : 
```javascript
<DropdownAlert ref={dropDownAlertRef} updateStatusBar={false} translucent />
```

**Comment by testshallpass** [comment]
Closing, see StatusBar props: https://github.com/testshallpass/react-native-dropdownalert/blob/master/docs/PROPS.md#statusbar
