### ISSUE TITLE
Add support for iOS and Android like notifications

### ISSUE THREAD

**Issue by testshallpass** [testshallpass/react-native-dropdownalert#23]
Thinking about adding alert types that are styled similar to the built in ones provided by Android and iOS. (👍  if you agree) Here are some screenshots of them: 

iOS
![iosnotification](https://cloud.githubusercontent.com/assets/7293079/19793079/e785a05c-9c98-11e6-99d7-43a77aba5daa.png)

android
![androidnotification](https://cloud.githubusercontent.com/assets/7293079/19793115/4837e540-9c99-11e6-9269-2f708b92ca0b.png)

**Comment by devBrian** [comment]
I have been experimenting and prototyping and have reached an ideal solution to add this feature in. I will be adding a branch and I will continue to finalize it. It is a major change so will be for 3.0.0.

**Comment by devBrian** [comment]
A usage example: 

```javascript
    const values = {
      bigImage: 'https://facebook.github.io/react/img/logo_og.png',
      smallImage: 'https://facebook.github.io/react/img/logo_og.png',
      cancelImage: 'https://facebook.github.io/react/img/logo_og.png',
      image: 'https://facebook.github.io/react/img/logo_og.png',
      header: 'Messenger',
      timestamp: '59m ago',
      title: 'Capitalize on low hanging fruit',
      username: 'username@company.com',
      message: 'Podcasting operational change management inside of workflows to establish a framework.',
      actions: [{text: 'Reply', callback: this.onAction}, {text: 'Archive', callback: this.onAction}]
    }
    this.dropdown.alertWithData(values, (alertData) =>{
      console.log(alertData);
    })
```

**Comment by ma-pe** [comment]
any news on this? i am exited about this feature.

**Comment by testshallpass** [comment]
I am going to revisit this. Which notification would be priority for you? iOS or Android @ma-pe

**Comment by ma-pe** [comment]
I have no priority since I am interested in both :)

**Comment by tandat2209** [comment]
Any updates?

**Comment by testshallpass** [comment]
@tandat2209 Checkout the open PR #150 this is attempt at it and I have some feedback I am waiting on.

**Comment by testshallpass** [comment]
Also, as far as this feature, it's next in line after 3 other features + 1 enhancement are complete.

**Comment by tandat2209** [comment]
@testshallpass  Thanks, I will check it out 👍

**Comment by saadmutahar** [comment]
@testshallpass Is this feature added?

**Comment by azhararmar** [comment]
It would also be great to have `renderContainer()` where it allows us to design our own custom alert type.

**Comment by testshallpass** [comment]
Closing as will not support this internally as the notification UI/UX can update from time to time hence is too much to manage in this library. However, can take advantage of new `children` prop in latest release (v5.0.0) to build your own alert (BYOA). I have done this myself in the example project to recreate these notifications. Check out: [NotificationAndroid](https://github.com/testshallpass/react-native-dropdownalert/blob/main/example/NotificationAndroid.tsx) and [NotificationIOS](https://github.com/testshallpass/react-native-dropdownalert/blob/main/example/NotificationIOS.tsx)
