### ISSUE TITLE
Extra height seen after the dropdown alert is closed.

### ISSUE THREAD

**Issue by kamalpandey** [testshallpass/react-native-dropdownalert#231]
#### Short Description

The drop down alert is working fine but after it is closed extra height equal to the height of the status bars gets added moving the header below. This problem occurred after upgrading Expo from 35 to 36.

#### Steps to Reproduce / Code Snippets / Usage

![Screenshot_20200728-181026 (1)](https://user-images.githubusercontent.com/4987931/88666552-f098b900-d0ff-11ea-8d00-4638535d6823.jpg)
![Screenshot_20200728-181038 (1)](https://user-images.githubusercontent.com/4987931/88666595-03ab8900-d100-11ea-8e07-df60060ec42b.jpg)
![Screenshot_20200728-181046 (1)](https://user-images.githubusercontent.com/4987931/88666609-0a3a0080-d100-11ea-8d5e-f0f68da17b57.jpg)

#### Expected Results

Should not add the new height

### Additional Information

* React Native version: [0.62]
* react-native-dropdownalert version: [4.3.0]
* Platform(s) (iOS, Android, or both?): [Android]

```
import DropdownAlert from "react-native-dropdownalert";
<DropdownAlert
          ref={ref => DropDownHolder.setDropDown(ref)}
          closeInterval={10000}
          panResponderEnabled={false}
          successColor={Colors.positive}
          infoColor={Colors.slate2}
          warnColor={Colors.warning}
          errorColor={Colors.negative}
          renderImage={this.renderLeftImage}
          renderTitle={() => <View />}
          replaceEnabled={false}
          onClose={data => this.handleAlertClose(data)}
          messageStyle={styles.alertMessageStyle}
        />

```

**Comment by mmehmetAliIzci** [comment]
I have the same problem even without expo

**Comment by mmehmetAliIzci** [comment]
Adding `updateStatusBar={false}` fixed the issue for me @kamalpandey

**Comment by kamalpandey** [comment]
Thanks @mmehmetAliIzci I already resolved it and forgot to mention here.
