### ISSUE TITLE
DropdownAlert is always hidden when Modal is true (react-native-modal)

### ISSUE THREAD

**Issue by Joshmatjjen** [testshallpass/react-native-dropdownalert#237]
#### Short Description

Any time Modal is true,  Dropdown alert dont show the message component, only statusbar color changes
when using react-native-modal
#### Steps to Reproduce / Code Snippets / Usage

```
<DropdownAlert
            ref={(ref) =>
              setDropDown(
                ref,
                pingTimeout,
                'error',
                'Disconnected',
                'No Internet Connection Or No Data Subscription',
              )
            }
            inactiveStatusBarStyle={barStyle}
            inactiveStatusBarBackgroundColor={color}
            zIndex={20}
            // wrapperStyle={{ position: 'absolute', zIndex: 344444444 }}
          />
```

#### Expected Results

DropDownAlert should be shown when modal is true

### Additional Information

* React Native version: 0.63.3
* react-native-dropdownalert version:  ^4.3.0
* Platform(s) (iOS, Android, or both?): Android
* iOS version: -
* Android version: Pie (9)

**Comment by djintalkalan** [comment]
Make a custom Modal.
Here I am using Modal from 'react-native'. you can use any modal of your choice.

Custom Modal:- 

import React, { useEffect, useRef } from 'react'
import { Modal as RNModal, ModalProps, View } from 'react-native' // import Modal of  your choice.
import DropdownAlert from 'react-native-dropdownalert'
import { DropDownHolder } from 'utils/DropdownHolder' // Dropdown Holder also mentioned below

export const CustomModal = (props: ModalProps & { children: any }) => {
    const dropDownRef = useRef<DropdownAlert>()

// Setting modalDropdown ref on visibility change of modal
    useEffect(() => {
        if (props?.visible) {
            setTimeout(() => {
                DropDownHolder.setModalDropDown(dropDownRef.current);
            }, 0);
        }
        return () => {
            DropDownHolder.setModalDropDown(null);
        }
    }, [props?.visible])

    return (
        <RNModal {...props} >
            <View style={{ flex: 1 }} > // This wrapping is very important
                {props.children}
            </View>
            <DropdownAlert ref={dropDownRef} />
        </RNModal>
    )
}


DropDownHolder:- 

import DropdownAlert from "react-native-dropdownalert";
type AlertType = 'info' | 'warn' | 'error' | 'success'
export class DropDownHolder {
    static dropDown: DropdownAlert | null | undefined;
    static modalDropDown: DropdownAlert | null | undefined;
    static setDropDown(dropDown: DropdownAlert | null | undefined) {
        this.dropDown = dropDown;
    }
    static setModalDropDown(dropDown: DropdownAlert | null | undefined) {
        this.modalDropDown = dropDown;
    }

    static getDropDown() {
        return this.dropDown;
    }

    static alert(type: AlertType, title: string, message: string) {
        if (message)
            (this.modalDropDown || this.dropDown)?.alertWithType(type, title, message) // this is very important
    }

}


In this, whenever any modal is visible, DropdownAlert's ref is updated in the Dropdown holder and will be removed on modal hide.
Hope it will work

**Comment by testshallpass** [comment]
This is a known caveat as either `Modal` or `react-native-modal` takes precedence. However, if you place `<DropdownAlert />` in the modal's document tree then use that so it can be seen.
