### ISSUE TITLE
does it support the RTL?

### ISSUE THREAD

**Issue by shaghayegh70** [testshallpass/react-native-dropdownalert#238]

**Comment by testshallpass** [comment]
Hi @shaghayegh70  I'm not too sure. What does RTL stand for? What are requirements to support it?

**Comment by AmmarMohamadIsmaeel** [comment]
@testshallpass Right To Left Like the Arabic Language for example

**Comment by 77TecShaeer** [comment]
+++++

**Comment by testshallpass** [comment]
I want to say "yes, it is already supported without any additional changes" as I tried `I18nManager.forceRTL(true);` and it rendered as expected. Was there more to it than that? @shaghayegh70

**Comment by testshallpass** [comment]
Closing as stale.
