### ISSUE TITLE
Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by gre-dev** [testshallpass/react-native-dropdownalert#253]
#### Short Description

I Cannot import the module because it's showing the following error!

![IMG_0147](https://user-images.githubusercontent.com/59331174/123663229-dfd85200-d83e-11eb-990f-de65d5360aaf.jpg)

#### Steps to Reproduce / Code Snippets / Usage

I don't know how to reproduce it on your end but the problem occured after facing some problems with react-native-gesture-handler. I fixed them and then I see this error. (I mean that react-native-dropdownalert was working well before that).

#### Trying to solve it...

- I tried to remove it from the dependencies then reinstalled it;
- I tried to remove the node_modules directory then running "yarn install";
- I tried to remove and reinstall the Pods'
- I restarted the machine & the iPhone device;
- I rebuilt the app also.

### Additional Information

* React Native version: 0.64.2
* react-native-dropdownalert version: 2.13.0
* Platform(s) (iOS, Android, or both?): iOS
* iOS version: 14.4.2

**Comment by gre-dev** [comment]
I just tried to comment out the line 29 of node_modules/react-native-dropdownalert/DropdownAlert.js then it's working well now !
![Screenshot 2021-06-28 at 18 43 24](https://user-images.githubusercontent.com/59331174/123665205-bb7d7500-d840-11eb-8885-72b6f98f9fc9.png)

**Comment by gre-dev** [comment]
I fixed it just by changing line no. 29 from `containerStyle: View.propTypes.style,` to `containerStyle: ViewPropTypes.style,`.

Don't forget to import `ViewPropTypes` in the same way you do to import the `View`, `Text` or `Modal`.

**Comment by testshallpass** [comment]
@gre-dev This was fixed in commit https://github.com/testshallpass/react-native-dropdownalert/commit/c6f541dacca10e9109a83a12b920af361348b01d and released in v3.5.0. With that said, I recommend upgrading to the latest version v4.3.0.
