### ISSUE TITLE
StatusBar is still light-content after use on iOS

### ISSUE THREAD

**Issue by testshallpass** [testshallpass/react-native-dropdownalert#29]
#### Issue Description

StatusBar remains `light-content` when predefined types are used.

#### Steps to Reproduce / Code Snippets

1. Use one of the predefined types.
2. Do not have `<StatusBar />` in parent
3. Notice it's still `light-content` after it's gone

#### Expected Results

Perhaps give a prop to enable or disable the change or remove completely.

### Additional Information

* React Native version: 0.40.0
* react-native-dropdownalert version: 2.5.0
* Platform(s) (iOS, Android, or both?): iOS

**Comment by devBrian** [comment]
A workaround: 

```javascript
//...
render() {
  return (
   <StatusBar barStyle={this.state.barStyle} />
  )
}
//...
  onClose(data) {
    this.setState({
      barStyle: 'default'
    })
  }
// ...
```

**Comment by michaelduminy** [comment]
This is also affecting me on Android. The status bar remains the colour of the alert that has been dismissed.

**Comment by devBrian** [comment]
hi @michaelduminy I updated the workaround above. I'm thinking either dropping support to change the StatusBar style and/or I can toggle back to default styles onDismiss for predefined types.

**Comment by insraq** [comment]
In my opinion, the component should remember the `barStyle` before and revert to that value afterwards.

**Comment by testshallpass** [comment]
hi @insraq That would be ideal but StatusBar does not provide a way to access the current barStyle.
