### ISSUE TITLE
Add argument to determine how alert was closed

### ISSUE THREAD

**Issue by morrislaptop** [testshallpass/react-native-dropdownalert#31]
#### Issue Description

No way to determine how the alert was closed (timeout, press, pan)

#### Steps to Reproduce / Code Snippets

1. Open alert
2. Close it
3. Only arguments received to onClose are type, title, message

#### Expected Results

Event function should receive an additional prop for method - timeout, press or pan

### Additional Information

* React Native version: 0.40.0
* react-native-dropdownalert version: 2.4.0
* Platform(s) (iOS, Android, or both?): both

**Comment by devBrian** [comment]
I like it as it's quite simple but this might beg the question if it needs to go a little further and make separate prop callback functions for each type. That way the receiver can do specific logic for whatever type it is. What you think?

**Comment by morrislaptop** [comment]
I think that would be better and have done so :) 

I was also looking for a way to attach data to the notification so I can know more about the context of the pop up (i"m using this to handle notifications in the foreground)
