### ISSUE TITLE
TypeError: Cannot read property 'style' of undefined, js engine: hermes React Native

### ISSUE THREAD

**Issue by gausu60** [testshallpass/react-native-dropdownalert#313]
I have Install package react-native-image-slider-box 
My code ": 
import React, { useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { SliderBox } from "react-native-image-slider-box";

const ProductImageGallery = () => {
  const [images, setImages] = useState([
    "https://www.thinkrenta.com/Products/_M_23TR Teak Álvaro Single Bed Non Storage.webp",
    "https://www.thinkrenta.com/Products/_M_23TR Teak Álvaro Single Bed Non Storage.webp",
    "https://www.thinkrenta.com/Products/_M_23TR Teak Álvaro Single Bed Non Storage.webp",
    "https://www.thinkrenta.com/Products/_M_23TR Teak Álvaro Single Bed Non Storage.webp",
  ]);

  return (
    <View style={styles.container}>
      <SliderBox
        images={images}
        onCurrentImagePressed={index => console.warn(`image ${index} pressed`)}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  }
});

export default ProductImageGallery;
TypeError: Cannot read property 'style' of undefined, js engine: herme this error occured anyone fix it

**Comment by testshallpass** [comment]
I don't see `style` or `styles` used in your code here. Maybe an issue in another component. That said, this not related to `react-native-dropdownalert` so closing.
