### ISSUE TITLE
Android StatusBar background not always resetting to transparent.

### ISSUE THREAD

**Issue by ryanhomer** [testshallpass/react-native-dropdownalert#35]
#### Issue Description

I'm using a StatusBar with `translucent={true}`. I've added an `endDelta` equal to the height of my status bar. When the DropdownAlert shows, the StatusBar takes on the background colour of the alert box. I'm also exclusively using the cancel button for interactive closing. This works as expected. However, if I use the DropdownAlert's reference and call `dismiss()` from `componentDidUpdate`, the status bar's background colour is not reset to transparent. 

Any suggestions on what I might try to rectify this? I've tried dismissing from `componentWillReceiveProps` as well but same result. I've also tried to delay the dismissal with `setTimeout` and no change either.

Thanks in advance for your help.

#### Steps to Reproduce / Code Snippets
```javascript
    componentDidUpdate(prevProps, prevState) {
        if (prevProps.alerts !== this.props.alerts) {
            const alert: Alert = this.props.alerts ? this.props.alerts[0] : null;
            if (alert) {
                if (this.alertId && alert.id !== this.alertId) {
                    console.debug('Top alert is different, dismissing Alert.');
                    this._dismissAlert();
                }
                this._showAlert(alert);
            } else {
                console.debug('All alerts removed, dismissing Alert.');
                this._dismissAlert();
            }
        }
    }

    _showAlert(alert: Alert) {
        this.alertId = alert.id;
        this._dropdownalert.alertWithType(
            alert.type,
            alert.title,
            alert.message,
        );
    }

    _dismissAlert() {
        if (this.alertId) {
            this._dropdownalert.dismiss();
            this.alertId = null;
        }
    }

    handleDropDownAlertCancel = () => {
        this._dismissAlert();
        this.props.removeOldestAlert();
    }

    render() {
        return(
            <View style={ styles.root }>
                <StatusBar
                    animated={true}
                    translucent={true}
                    backgroundColor='#FFFFFF24'
                />
                    <Navigator
                        ...
                    />
                {/* !!! Make sure DropdownAlert is last component in doc tree. */}
                <DropdownAlert
                    ref={(ref) => this._dropdownalert = ref}
                    showCancel
                    closeInterval={0}
                    messageNumOfLines={0}
                    tapToCloseEnabled={false}
                    panResponderEnabled={false}
                    endDelta={StatusBar.currentHeight}
                    onCancel={this.handleDropDownAlertCancel}
                    onClose={(data) => { this.props.removeOldestAlert(); }}
                />
            </View>
        );
    }
```
#### Expected Results

The status bar should return to its previous state, i.e. transparent.

### Additional Information

* React Native version: 0.41.0
* react-native-dropdownalert version: 2.5.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by testshallpass** [comment]
Hi @ryanhomer Issue #29 is related to this. I just updated the workaround. The module does apply background color to the status bar for Android. You could also try using ```custom``` type and provide a background color using containerStyle prop. Hope this helps.

**Comment by ryanhomer** [comment]
Thanks. This helped me to solve my issue.
