### ISSUE TITLE
Cannot read property 'alertWithType' of undefined

### ISSUE THREAD

**Issue by Margoot** [testshallpass/react-native-dropdownalert#40]
#### Issue Description

I'm using NavigatorIOS and Navigator(for Android) and the dropdown ref is not recognized in my component. It seems undefined due to the navigator which has also a ref. 
How could I handle this error ? 

Thank you for your help ! 

### Additional Information

* React Native version: 0.41.2
* react-native-dropdownalert version: latest
* Platform(s) (iOS, Android, or both?): both

**Comment by testshallpass** [comment]
hi @Margoot Can you post code snippet of the both refs and usage?

**Comment by Margoot** [comment]
Thank you testshallpass for your reply.

My navigator renders all the views which contain ErrorMessage Component. 
The navigator has a ref 'nav' and the ErrorMessage component has a ref 'dropdown'. 
Dropdown is not recognized in my component, is undefined. 

Here is my ErrorMessage component to handle errors in the whole app's views : 

```
export default class ErrorMessage extends Component {

  constructor(props) {
    super(props);
  }

  componentDidMount() {
    this.dropdown.alertWithType('error', 'Error', this.props.errorMessage);
  }

  render() {
    if (this.props.error) {
      return(
       <DropdownAlert
        ref={(ref) => this.dropdown = ref}
        onClose={(data) => console.log("close")} />
      )
    } else {
      return null;
    }
  }
}
```


Here is my Navigator for iOS ans Android which wrappes all the views : 
```
render() {
    if (Platform.OS === 'ios') {
      return (
       <NavigatorIOS
        ref='nav'
        tintColor="white"
        style={{flex: 1}}
        initialRoute={{
          title: 'Splash',
          navigationBarHidden: true,
          component: SplashScene,
        }}
       />
      );
    } else {
      return (
       <Navigator
        ref='nav'
        initialRoute={{
          title: 'SplashScreen',
          component: SplashScene,
          display: false
        }}
        renderScene={(route, navigator) =>
         <route.component {...route.passProps} navigator={navigator}/>
        }
        navigationBar={<NavigationBar
         style={Style.navigationBar}
         routeMapper={NavigationBarRouteMapper}
        />}
        configureScene={() => {
          return Navigator.SceneConfigs.FloatFromRight;
        }}/>
      );
    }
```
Thank you for your help

**Comment by testshallpass** [comment]
Hi @Margoot I think there might be an issue with `this.props.error` in the ErrorMessage render as in should it be `this.props.errorMessage` or is this a prop invoked elsewhere?  

Also, string refs will be deprecated in the future, I suggest changing `ref='nav'` to `ref={(ref) => this.navigator = ref}`

One more thing is, can you tell me if `this.dropdown` itself is undefined?

**Comment by Margoot** [comment]
Hi @testshallpass and thank your reply ! 

This.props.errorMessage works well, I can display this props inside a Text tag. 

Thank you for the syntax of the ref. 

When I do a console log of "this.dropdown", it's "undefined". As if inside the navigator that has a ref, I could not put subcomponent with a ref... 

Thanks for your help :)

**Comment by testshallpass** [comment]
Hi @Margoot No problem. 

So if it's `undefined` I'm thinking the render method might be returning `null`. Can you log out the `this.props.error` and see if it's false or null or undefined?

Also, can you provide code snippet of where the ErrorMessage component is mounted?

**Comment by testshallpass** [comment]
A friendly suggestion, you might want to add propTypes and defaultProps like so: 

```javascript
static propTypes = {
     errorMessage: React.PropTypes.string,
     error: React.PropTypes.bool
}
static defaultProps = {
    errorMessage: 'Something went wrong.',
    error: false
}
```

**Comment by Margoot** [comment]
Hi @testshallpass, 

My two props work fine. When I log out "this.props.error", it's false (because there isn't any error for the moment). 
Before using the dropdown module, I displayed the errors using a text tag and it worked very well
I think the problem comes from my DropdownAlert reference which is not recognized.

Here is the code where the ErrorMessage component is mounted: 
I called this component at the end of my login view. If a user not fill in all the fields, props.error = true and props.errorMessage = custom error message. 
```
<View>
       <ErrorMessage errorMessage={props.errorMessage} error={props.error}/>
</View>
```
Thank you for your help !

**Comment by testshallpass** [comment]
Hi @Margoot, Sorry for delay. 

I think what might fix this is if there was a visible prop on DropdownAlert. In a sense, a replacement for `alertWithType`. But for now, I would advise adding DropdownAlert to Login directly.

```javascript
       <DropdownAlert
           visible={true|false}
           type={'error'}
           title={'Error'}
           message={'Something went wrong.'} />
```

Hope this helps.

**Comment by testshallpass** [comment]
Closing. Feel to reopen if problem persists or need more help.
