### ISSUE TITLE
Transulenct property on android device

### ISSUE THREAD

**Issue by gcmartins93** [testshallpass/react-native-dropdownalert#41]
#### Issue Description
Wouldn't be greate to add support to translucent status bar on android devices?

#### Steps to Reproduce / Code Snippets
Setting StatusBar to translucent on android devices causes dropdownalert to render as shown below:
```jsx
<StatusBar backgroundColor='transparent' translucent={ true } barStyle="light-content"/>
```
![Result](http://i.imgur.com/71PEoes.png)

#### Possible solution
Adding an additional paddingTop when StatusBar is translucent, based on StatusBar height, may fix it:
```javascript
if (Platform.OS === 'android' && this.props.translucent) {
  style = [style, { paddingTop: StatusBar.currentHeight }]
}
```

### Additional Information

* React Native version: 0.41.0
* react-native-dropdownalert version: 2.3.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by testshallpass** [comment]
Hi @gcmartins93 Can you fix result image it's not showing up for me? I had one question, do you use the pre-defined types or custom? I was also thinking about taking out StatusBar handling. See #29.

**Comment by testshallpass** [comment]
Hi @gcmartins93 I welcome a PR if you fix this

**Comment by gcmartins93** [comment]
Hi @testshallpass, result image updated. I've fixed it as mentioned in the "Possible solution" section. I'm going to do a PR for this.
