### ISSUE TITLE
Code not respecting that styles arent always objects

### ISSUE THREAD

**Issue by robcalcroft** [testshallpass/react-native-dropdownalert#45]
#### Issue Description

When passing a style as a prop, it is not always an object, sometimes its a StyleSheet reference ie. a number. The code in places assumes it is an object and as such some functionality does not work.

#### Steps to Reproduce / Code Snippets

```javascript
const styles = StyleSheet.create({container: { backgroundColor: 'red' }});

<Dropdown containerStyle={styles.container} />
```
`styles.container` actually resolves to a number not an object and as such on line [359](https://github.com/testshallpass/react-native-dropdownalert/blob/master/DropdownAlert.js#L359) of DropdownAlert.js the `backgroundColor` is `undefined` as it is assuming an object

#### Expected Results

The code should flatten incoming styles itself OR make it clear in the docs that you need to flatten your styles using `StyleSheet.flatten()`.

### Additional Information

* React Native version: 0.42.1
* react-native-dropdownalert version: 2.6.2
* Platform(s) (iOS, Android, or both?): Both

**Comment by testshallpass** [comment]
Hi @robcalcroft I want to have the best of both worlds. How do you detect whether or not it needs to be flat? If not possible no worries I am open to applying flatten to ensure ease of use.
