### ISSUE TITLE
Can't differentiate between swipe to close and tap to close. (Action param missing?)

### ISSUE THREAD

**Issue by MossP** [testshallpass/react-native-dropdownalert#46]
#### Issue Description

`action` param not received by onClose()

#### Steps to Reproduce / Code Snippets

Trigger a custom message via `alertWithType()`, swipe to dismiss, tap to dismiss, or just allow it to dismiss naturally. the call backs are all identical meaning that you cannot respond based on the users input.

#### Expected Results

An action param should be received by the onClose() function.

### Additional Information

* React Native version: 0.42
* react-native-dropdownalert version: 2.6.2
* Platform(s) (iOS, Android, or both?): iOS (only tested on iOS)

**Comment by testshallpass** [comment]
Hi @MossP I noticed this too. It's like my changes did not make the 2.6.2 release. I will bump version and see if this addresses it.

**Comment by testshallpass** [comment]
Hi @MossP Please install latest (2.7.0) and look for the `action` in the callback payload. Thanks.

**Comment by MossP** [comment]
Hi @testshallpass - Thanks for the swift response!

I've just had a look and I can confirm that I now see `tap`, `pan` and `automatic` action parameters in the callback. Many thanks!
