### ISSUE TITLE
I get the DropdownAlert everytime I start the app

### ISSUE THREAD

**Issue by itswaze** [testshallpass/react-native-dropdownalert#51]
Hey!

Im using this library to show an error when the user has no internet connection.
But everytime I start the app, even with WiFi on I get the message saying that I have no internet, after that it works perfectly when I am on the app and switch on and off the wifi.
(On real device testing)

Unrelated question: Can this be used as a component? I want to be able to add this to my index or something and show this error on all screens without having to manually add the code to each screen. Any example would be great :)

**Comment by testshallpass** [comment]
Hi @itswaze If you are using NetInfo, I recall having the same issue. In my experience, it worked best on real device. Also, what worked best was adding the listener first on the contrary to what docs say.
```javascript
NetInfo.addEventListener(
  'change',
  handleFirstConnectivityChange
);
```
It sure can. You can read more on how in this issue: Add Providers for simplification #30 You can also see I'm looking to improve the module to help this further.
