### ISSUE TITLE
[Android] Alert show up below of the NavBar

### ISSUE THREAD

**Issue by cristiankmb** [testshallpass/react-native-dropdownalert#53]
i wanted like use a awesome alert, then i installed and running this tool on my react-native project, This worked good on iOS, however when i try run in Android have a problem. The Alert was show below of the NavBar. I reader all docs from site and i not found the way to resolve this, I thinking that is a issue.

-Download:  react-native-dropdownalert/example
-Use terminal and navigate to the example directory: cd /Example
-Install the npm modules: npm install
-Link: react-native link
-Check that the folder node_modules was installed.
-Use a NavBar on main.js (I used native-base components)
-Run project: react-native run-android
-Show alert: Press some button to show alert

Result Android:
Alert was show below of the NavBar

native-base: ^2.1.3,
react: ^16.0.0-alpha.6,
react-native: ^0.43.4,
react-native-dropdownalert: ^2.8.0

Platform: Android
Device: Emmulator and RealDevice

**Comment by testshallpass** [comment]
Hi @cristiankmb I am able to reproduce this and I tried a couple things like changing the [zIndex](http://facebook.github.io/react-native/releases/0.44/docs/layout-props.html#zindex) and moving the `<Header />` and `<DropdownAlert />` components up and down the document tree. Unfortunately, none of these addressed the issue. Some good news though I was able to get the alert to appear above the header by adding the DropdownAlert to the header's document tree but this does not have desired results. I am also starting to think it might be more of an issue on the native-base side than DropdownAlert. 

Can you open a ticket there and then we can continue to discuss? Thanks

**Comment by testshallpass** [comment]
https://github.com/GeekyAnts/NativeBase/issues/912

**Comment by testshallpass** [comment]
Closing this to defer to https://github.com/GeekyAnts/NativeBase/issues/912

**Comment by alawneh0** [comment]
I have the same issue, I am using react-native-router-flux 
can anyone help?
