### ISSUE TITLE
Option to disable components StatusBar logic.

### ISSUE THREAD

**Issue by grundmanise** [testshallpass/react-native-dropdownalert#56]
#### Issue Description

Thanks for this useful plugin.
Currently we are unable to use this plugin with `UIViewControllerBasedStatusBarAppearamce: YES`.
There should be a prop to disable libs. StatusBar logic.

### Additional Information

* React Native version: 0.44 with WIX/react-native-navigation
* react-native-dropdownalert version: 2.8.0
* Platform(s) (iOS, Android, or both?): iOS

**Comment by testshallpass** [comment]
Hi @grundmanise I agree and I'm on it.

**Comment by testshallpass** [comment]
hi @grundmanise Please review PR #57

**Comment by grundmanise** [comment]
Hi @testshallpass , thanks for the promptness, looks good.

**Comment by marcosinigaglia** [comment]
Hi @testshallpass , do you soon release a new version?
