### ISSUE TITLE
Not positioned at top changes StatusBar, has paddingTop and pan responder is up

### ISSUE THREAD

**Issue by testshallpass** [testshallpass/react-native-dropdownalert#59]
#### Issue Description

DropdownAlert not positioned at top changes StatusBar and has paddingTop. Also, if trying to dismiss with pan responder it is an up gesture.  Related to #58 

#### Steps to Reproduce / Code Snippets
1. Use startDelta and endDelta to move the alert's position. (i.e. bottom) 
2. Invoke the alert
3. Notice the StatusBar changes
4. Notice the paddingTop (predefined types)
5. Notice pan responder is up gesture

#### Expected Results
StatusBar should not change and paddingTop should be eliminated if not positioned at the top. Pan responder should be gesture up for first half of height window and second half should be down gesture.

### Additional Information

* React Native version: 0.43.4
* react-native-dropdownalert version: 2.8.0
* Platform(s) (iOS, Android, or both?): both

**Comment by testshallpass** [comment]
Won't fix the statusBar change but can use `updateStatusBar` prop to control it.

**Comment by testshallpass** [comment]
Won't fix the pan responder as it can be changed with `panResponderEnabled` prop

**Comment by testshallpass** [comment]
Won't fix

**Comment by marcosinigaglia** [comment]
Is there a way to expose the defaultContainer's paddingTop value?

**Comment by testshallpass** [comment]
That's next on my todo list. @marcosinigaglia
