### ISSUE TITLE
How to use this when app exist?

### ISSUE THREAD

**Issue by WangJian0** [testshallpass/react-native-dropdownalert#60]
#### Issue Description
I want to use it when app exist,but its not show.
Could you give me some proposes?
Thanks

* React Native version: [FILL THIS OUT]   0.44.0
* react-native-dropdownalert version: [FILL THIS OUT]   latest
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]  Android

**Comment by testshallpass** [comment]
Hi @WangJian0 I think I'm going to need more info. What do you mean by "app exist"?

**Comment by WangJian0** [comment]
I mean that the app is running in the background, how to use it and let it show？

**Comment by testshallpass** [comment]
@WangJian0 If the app is the background it will be out of scope so will not be able to show it. You might want to look into implementing push notifications.

**Comment by WangJian0** [comment]
OK.Thanks.
