### ISSUE TITLE
useNativeDriver

### ISSUE THREAD

**Issue by jackread** [testshallpass/react-native-dropdownalert#61]
You should add ```useNativeDriver: true``` to your alert animations for an extra smooth transition!

https://facebook.github.io/react-native/blog/2017/02/14/using-native-driver-for-animated.html

**Comment by jackread** [comment]
Something like this...

<pre><code>animate(toValue) {
  Animated.spring (
    this.state.animationValue, {
      toValue: toValue,
      useNativeDriver: true,
      duration: this.state.duration,
      friction: 9
    }
  ).start()
}</code></pre>

**Comment by testshallpass** [comment]
Hi @jackread Good idea. Do you know any limitations (i.e. react-native version)?

**Comment by jackread** [comment]
Hey sorry for the slow reply.

Yup. 0.40.0 and up... also you can only use it on transforms/opacity etc. stuff that affects flexbox etc. is a no go (zIndex, margins etc.)
