### ISSUE TITLE
Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.

### ISSUE THREAD

**Issue by ivpusic** [testshallpass/react-native-dropdownalert#64]
I am getting above warning with rn 0.44

**Comment by testshallpass** [comment]
Hi @ivpusic Yeah if you have React >15.5.0 it will warn about it. In 16 aka React Fiber it will be required to migrate to "prop-types" package.

**Comment by testshallpass** [comment]
Unfortunately, ViewPropTypes will break on react-native versions earlier than 0.44.0. 

[Expose new ViewPropTypes](https://github.com/facebook/react-native/commit/9a88c721635ddb1ad6624b7dd3fc9e21530b00e2)

**Comment by testshallpass** [comment]
[View.propTypes to ViewPropTypes](https://github.com/facebook/react-native/commit/53905a537a58d028fc5eb1c4e9a8ec967d8cd396)

**Comment by ivpusic** [comment]
sure, that's why npm versions are here. People with rn 0.44 can use version < X, and people above 0.44 can use >= X. As the message says, `View.propTypes` will be removed, so this warning has to be fixed for future versions.

What you could do is to remove `View.propTypes` usage in your code, as it is used only here https://github.com/testshallpass/react-native-dropdownalert/blob/master/DropdownAlert.js#L29. Should be easy to switch to `prop-types` version.
