### ISSUE TITLE
no animation appers after invoke `alertWithType` one more time, the drop-message show 

### ISSUE THREAD

**Issue by sopaco** [testshallpass/react-native-dropdownalert#65]
#### Issue Description
no animation appers after invoke `alertWithType` one more time, the drop-message show immediately

#### Steps to Reproduce / Code Snippets
invoke `alertWithType` twice or more times

#### Expected Results
the drop-message shows with an animation

### Additional Information

* React Native version: 0.44.0
* react-native-dropdownalert version: 2.9.0
* Platform(s) (iOS, Android, or both?): android

**Comment by testshallpass** [comment]
Hi @sopaco I have pinpointed the issue. `useNativeDriver` was added recently to the animation block and this causes the issue. Feel free to rollback to 2.8.0 and be on the lookout for 2.10.0 with the fix.
