### ISSUE TITLE
DropdownAlert on top of Modal

### ISSUE THREAD

**Issue by stereodenis** [testshallpass/react-native-dropdownalert#66]
#### Issue Description

DropdownAlert is below Modal

#### Steps to Reproduce / Code Snippets

Open Modal, then open DropdownAlert

![iphone 5 ios 10 2 14c89 2017-06-05 18-55-53](https://cloud.githubusercontent.com/assets/1406461/26792060/d1e7dc56-4a21-11e7-95de-04f2307238dd.png)

#### Expected Results

DropdownAlert on top of Modal

### Additional Information

* React Native version: 0.36.1
* react-native-dropdownalert version: 2.8.0
* Platform(s) (iOS, Android, or both?): iOS

**Comment by testshallpass** [comment]
Hi @stereodenis The way it behaves is expected. However, if you would like DropdownAlert to appear above the modal you would need to add DropdownAlert to the document tree of the the modal. Then invoke it as you see fit.

**Comment by stereodenis** [comment]
@testshallpass but I want to have one DropdownAlert, to use it through the Reflux

**Comment by testshallpass** [comment]
I'm not 100 % versed on Reflux. Can you share some implementation details?

**Comment by stereodenis** [comment]
Your recommendation works! Thanks

**Comment by laksh1010** [comment]
hi i am having the same issue. can you share a working code sample if you had. thanks a lot
