### ISSUE TITLE
Warning showed up, when the dropdown not dismissed and changing screen using react-navigation.

### ISSUE THREAD

**Issue by buncismamen** [testshallpass/react-native-dropdownalert#69]
#### Issue Description
Warning showed up, when the dropdown not dismissed and changing screen using react-navigation.
the warning error is 
```
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the DropdownAlert component.

```
#### Steps to Reproduce / Code Snippets

1 use react-navigation
2 use react-native-dropdownalert
3 navigate with react navigation to a screen (now app is in new screen so we can use back button)
4 make the app show dropdownalert in the new screen
5 press back button from hardware/back button from header to return to screen before step 3
6 the screen is changed to initial screen but
7 warning showed up

#### Expected Results

the warn shouldn't showed up,

I know it's more like a questions instead issues report,
I think the problem is because the dropdown is showed up in screen B while back button change in the screen A 

the warn is not showed up if we change screen when the dropdown is already dismissed.
### Additional Information

* React Native version: ^0.45.1
* react-native-dropdownalert version: ^2.10.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by testshallpass** [comment]
Hi @buncismamen  Allow ~400ms before you navigate to the next screen.

**Comment by buncismamen** [comment]
@testshallpass hi, what do you mean with Allow > 400 ms?, 

do you mean to give 400ms sec to make dropdown dismiss itself?

**Comment by testshallpass** [comment]
Hi @buncismamen Yes to both exactly. The dismiss animation duration is 400ms.
