### ISSUE TITLE
How to  set elevation property to Animated.View from dropdownalert

### ISSUE THREAD

**Issue by ShaileshPrajapati-BTC** [testshallpass/react-native-dropdownalert#70]
#### Issue Description

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

### Additional Information

* React Native version: [FILL THIS OUT]
* react-native-dropdownalert version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by testshallpass** [comment]
@ShaileshPrajapati-BTC I don't have the style attributes for Animated.View expose as props so you can't set it.
