### ISSUE TITLE
Hides immediately on android . 

### ISSUE THREAD

**Issue by manpreetmannysingh** [testshallpass/react-native-dropdownalert#72]
#### Issue Description

I am implementing this in my app and when i click button, error message showing but hides immediately.

#### Expected Results

I want to hide this alert after 4-5 seconds.

### Additional Information

* React Native version: "react-native": "0.45.1",
* react-native-dropdownalert version: "react-native-dropdownalert": "^2.10.0"
* Platform(s) (iOS, Android, or both?): android

**Comment by testshallpass** [comment]
Hi @manpreetmannysingh You can set `tapToCloseEnabled` to false and then programmatically dismiss it after 4-5 seconds with a timeout.

**Comment by manpreetmannysingh** [comment]
@testshallpass Can you please provide an example ?

**Comment by hrmoller** [comment]
I have the same issue and setting `tapToCloseEnabled={false}` doesn't help.

**Comment by hrmoller** [comment]
...however when switching of 'Debug JS Remotely' it does work as expected.

**Comment by jaredramirez** [comment]
I have the same issue as @hrmoller. And turning off 'Debug JS Remotely' does fix it for me as well

**Comment by testshallpass** [comment]
Hi @manpreetmannysingh What do you mean "click the button" like the alert's cancel button? Please provide a snippet of the DropdownAlert so I may examine the props you are using. 

To clarify if the alert is invoked again while it's present it will dismiss immediately and show the new alert.

**Comment by testshallpass** [comment]
Closing if you think it's still an issue, please open new issue with more details.

**Comment by jonatanrinckus** [comment]
I have the same issue when the "Debug JS Remotely" is enabled, when is off, it work's nice.
