### ISSUE TITLE
Stack Navigator

### ISSUE THREAD

**Issue by nephix** [testshallpass/react-native-dropdownalert#73]
#### Issue Description

When I use [StackNavigator](https://reactnavigation.org/docs/navigators/stack) with enabled header, the react-native-dropdownalert is displayed below the header and not at the top of the screen.

#### Steps to Reproduce / Code Snippets

1. Implement [StackNavigator](https://reactnavigation.org/docs/navigators/stack) example
2. Implement react-native-dropdownalert
3. Trigger the drop down

![Drop down alert below header](http://i.imgur.com/9MrkerP.png)

#### Expected Results

There should be a prop for the drop down alert to overlay above the header.

### Additional Information

* React Native version: 0.45.1
* react-native-dropdownalert version: 2.10.0
* Platform(s) (iOS, Android, or both?): iOS

**Comment by testshallpass** [comment]
Hi @nephix If you disable the StackNavigator header, does it work as expected? It appears that the dropdown alert is a child of StackNavigator, is that correct? There are `startDelta` and `endDelta` props that can change the dropdown alert position, perhaps these might help.

**Comment by nephix** [comment]
Hi testshallpass,

yes the dropdown alert is within the StackNavigator. I tried to workaround that with startDelta and endDelta but I was not able to render the dropdown "above" of the StackNavigator's header.

I worked around this by hiding the StackNavigator's header just before displaying the dropdown alert

**Comment by testshallpass** [comment]
Hi @nephix I was able to reproduce. It appears that react-navigation wraps it's contents in like a container. I reported to react-navigation to get some assistance: https://github.com/react-community/react-navigation/issues/2423

**Comment by ricardokdz** [comment]
+1

**Comment by manaka02** [comment]
+1

**Comment by slpereira** [comment]
This problem is happening to me as well. @testshallpass your issue on react-navigation was closed without any response, is there any workaround in this issue?

**Comment by testshallpass** [comment]
@slpereira I'm looking into workaround or solution.

**Comment by szantogab** [comment]
@testshallpass @slpereira @nephix Actually the solution is pretty straightforward. You need to place the `DropdownAlert` **ABOVE** the `StackNavigator`. 

I do it like this:

```
export class App extends React.Component {
    render() {
        return (
            <View style={{width: '100%', height: '100%'}}>
                <Nav/>
                <DropdownAlert ref={(ref) => DropDownHolder.setDropDown(ref)}/>
            </View>
        )
    }
}
```

Here `Nav` is your component that you want to start the application with.
I have a `DropDownHolder` in this solution to save this the dropdown reference for the entire app, so every component can access it:

```
export class DropDownHolder {
    static dropDown;

    static setDropDown(dropDown) {
        this.dropDown = dropDown;
    }

    static getDropDown() {
        return this.dropDown;
    }
}

```

Hope this helps. :)

**Comment by nephix** [comment]
Thanks a lot @szantogab!

**Comment by testshallpass** [comment]
Thanks @szantogab  Do you mind if I create a gist from your example and link it on README?

**Comment by szantogab** [comment]
@testshallpass Of course not. Go ahead! :)

**Comment by herarya** [comment]
@szantogab that worked! Thanks so much!

**Comment by SheppardX** [comment]
with router flux i cant do your fix because i have this as my start 

`let middleware = [
	Analytics,
	thunk, // Allows action creators to return functions (not just plain objects)
];

if (__DEV__) {
  // Dev-only middleware
	middleware = [
		...middleware,
		logger(), // Logs state changes to the dev console
	];
}

// Init redux store (using the given reducer & middleware)
const store = compose(
  applyMiddleware(...middleware),
)(createStore)(rootReducer);

/* Component ==================================================================== */
// Wrap App in Redux provider (makes Redux available to all sub-components)
export default function AppContainer() {
	return (
		<Provider store={store}>
			<RouterWithRedux scenes={AppRoutes} style={AppStyles.appContainer} />
		</Provider>
	);
}`

can u help me ? i have the same issue

**Comment by SheppardX** [comment]
@szantogab Your really helped me with redux + router flux ... i used the same method
```

export default function AppContainer() {
	return (
		<View style={AppStyles.container}>
			<Provider store={store}>
				<RouterWithRedux scenes={AppRoutes} style={AppStyles.appContainer}/>
			</Provider>
			<DropdownAlert ref={ref => DropDownHolder.setDropDown(ref)} closeInterval={6000}/>
		</View>
	);
}
```

And it works perfectly

**Comment by maharjanaman** [comment]
@szantogab great way to make it available on every component. But how can I trigger `alertWithType` on `componentDidMount` or `componentWillMount`? As it seems during this lifecycle refs has not been set or something. Is there some way to achieve this?

**Comment by szantogab** [comment]
@maharjanaman If you use `DropdownHolder` mentioned above, you can get a reference to the dropdown by doing `DropdownHolder.getDropdown().alertWithType(....)`

**Comment by maharjanaman** [comment]
@szantogab I'm try to show alert as soon as screen loads i.e. on `componentDidMount`. But when trying to call `alertWithType(...)` in `componentDidMount` method it gives error `TypeError: undefined is not an object (evaluating 'DropDownHolder.getDropDown().alertWithType')`

**Comment by xmannv** [comment]
@szantogab can you show more to control the onClose property in other component, feel like: 

`<DropdownAlert ref={ref => DropDownHolder.setDropDown(ref)} onClose={DropDownHolder.onClose}/>`

And in my DropDownHoler:
```
export class DropDownHolder {
  static dropDown
  static onClose

  static setDropDown (dropDown) {
    this.dropDown = dropDown
  }

  static getDropDown () {
    return this.dropDown
  }

  static setOnClose(onClose) {
    this.onClose = onClose
  }
}
```
In my component, i tried but seem like it didn't work with onClose

```
DropDownHolder.setOnClose(
() => {        
alert('did u call me')
 console.log('call me')
}
)

```

**Comment by NhatMai** [comment]
Thank szantogab

**Comment by stereodenis** [comment]
@xmannv my variant with typescript types
```
type AlertType = 'info' | 'warn' | 'error' | 'success'

export type DropdownType = {
  alertWithType: (type: AlertType, title: string, message: string) => void
}

export class DropDownHolder {
  static dropDown: DropdownType

  static setDropDown(dropDown: DropdownType) {
    this.dropDown = dropDown
  }

  static alert(type: AlertType, title: string, message: string) {
    this.dropDown.alertWithType(type, title, message)
  }
}
```

**Comment by testshallpass** [comment]
Added documentation to README with gists examples to help with StackNavigator. PR update readme with caveats #147

**Comment by abdul-elah-js** [comment]
how do you access the dropdown holder from another component ? @szantogab

**Comment by Aidenkwok** [comment]
+1

**Comment by testshallpasswork** [comment]
@abdul-elah-js `import DropDownHolder from './DropDownHolder'` then use it as described `DropDownHolder.getDropDown().alertWithType(....)`

**Comment by berk9595** [comment]
class App extends React.Component {
render() {
    const {hasAuth, citySelected} = this.state;
    return (
      <ApolloProvider client={client}>
        <MyContainer
            screenProps={{
              changeLoginState: this.handleLoginState,
              dropDownAlertRef: this.dropDownAlertRef,
            }}
          />
        **<DropdownAlert ref={ref => (this.dropDownAlertRef = ref)} />**
      </ApolloProvider>
    );
  }
}
-------------------------------------------------------------------------------------
class MyContainer extends React.Component {
    render(){
      return(
       <TouchableOpacity
              onPress={() => {
                **this.props.screenProps.dropDownAlertRef.alertWithType(
                  'success',
                  'Succes !!',
                  'Something nice !!',
                );**
              }}>
              <Text>
                Trigger Alert !
              </Text>
            </TouchableOpacity>
     )
    }
}

**Comment by berk9595** [comment]
```
class App extends React.Component{
    render(){
        return(
            <ApolloProvider client={client}>
                <MyContainer screenProps={{dropDownAlertRef: this.dropDownAlertRef}}/>
                <DropdownAlert ref={ref => (this.dropDownAlertRef = ref)} />
            </ApolloProvider>
        )
    }
}
```
--------------------------------------------------------------------------
```
class MyContainer extends React.Component {
render(){
return(
       <TouchableOpacity
              onPress={() => {
                this.props.screenProps.dropDownAlertRef.alertWithType(
                  'success',
                  'Succes !!',
                  'Something nice !!',
                );
              }}>
              <Text>
                Trigger Alert !
              </Text>
            </TouchableOpacity>
)
}
}
```

**Comment by afizboltz** [comment]
> @xmannv my variant with typescript types
> 
> ```
> type AlertType = 'info' | 'warn' | 'error' | 'success'
> 
> export type DropdownType = {
>   alertWithType: (type: AlertType, title: string, message: string) => void
> }
> 
> export class DropDownHolder {
>   static dropDown: DropdownType
> 
>   static setDropDown(dropDown: DropdownType) {
>     this.dropDown = dropDown
>   }
> 
>   static alert(type: AlertType, title: string, message: string) {
>     this.dropDown.alertWithType(type, title, message)
>   }
> }
> ```
> 
> so I just call `DropDownHolder.alert('error', 'Title', 'error message')`

hi, may I know did you put DropDownHolder as a component ?
