### ISSUE TITLE
changing statusbar color on android

### ISSUE THREAD

**Issue by aotapp** [testshallpass/react-native-dropdownalert#75]
statusbar color is changed to black when dismissing. Only on android

before showing error
![untitled](https://user-images.githubusercontent.com/13177405/28768658-1eead88c-75f6-11e7-811b-be40022e60e3.png)

when showing error
![untitled 2](https://user-images.githubusercontent.com/13177405/28768678-2ae4c4ea-75f6-11e7-8ebb-cad5378401de.png)

when dialog gone
![untitled 3](https://user-images.githubusercontent.com/13177405/28768681-2f7a0cc2-75f6-11e7-91b8-38ab1cbc499d.png)

**Comment by testshallpass** [comment]
Hi @aotapp Use `inactiveStatusBarBackgroundColor` prop to retain the color your app prefers after it dismisses or disable the color change completely using: `updateStatusBar` prop.
