### ISSUE TITLE
How do I display download progress?

### ISSUE THREAD

**Issue by Lizhooh** [testshallpass/react-native-dropdownalert#78]
#### Issue Description
I want to show download progress.

sample code:
```js
waittime = time => new Promise(rs => setTimeout(rs, time));

async componentDidMount() {
    this.dropdown.alertWithType('info', 'Download', 'downloaded 10%');
    await this.waittime(500);
    this.dropdown.alertWithType('info', 'Download', 'downloaded 20%');
    await this.waittime(500);
    this.dropdown.alertWithType('info', 'Download', 'downloaded 30%');
    await this.waittime(500);
    this.dropdown.alertWithType('info', 'Download', 'downloaded 40%');
}
```

but, each time i use `alertWithType`, there is an animation creation and destruction.

How to update its value before the `dropdownalert` has gone?

### Additional Information

* React Native version: 0.47
* react-native-dropdownalert version: 2.11.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by testshallpass** [comment]
Hi @Lizhooh You might want set `replaceEnabled` prop to `false` and then the alert will only state change vs replace itself and rerun animation.

**Comment by Lizhooh** [comment]
ok!
