### ISSUE TITLE
Warning: Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by acrocat** [testshallpass/react-native-dropdownalert#82]
#### Issue Description

A warning message about updating components appears if you unmount the active scene before the alert is dismissed.

#### Steps to Reproduce / Code Snippets

Trigger your alert and, before it dismisses, do something to unmount its parent component such as transitioning to a different scene in your stack.

#### Additional Information

* React Native version: 0.47.2
* react-native-dropdownalert version: 2.11.0
* Platform(s) (iOS, Android, or both?): iOS

I tried to get around this by dismissing the alert programmatically before the component unmounted but it didn't work.

**Comment by Maxeh** [comment]
@acrocat I have created a PR for this: #85
