### ISSUE TITLE
imageSrc not working

### ISSUE THREAD

**Issue by AlmogRnD** [testshallpass/react-native-dropdownalert#86]
I'm trying to set imageSrc but it's not changing  
imageSrc={'https://facebook.github.io/react/img/logo_og.png'} also tried local seems to be a bug 

* React Native version: Latest
* react-native-dropdownalert version: Lastest
* Platform(s) (iOS, Android, or both?): Andriod

**Comment by devbriguy** [comment]
Try passing `custom` as the type into the `alertWithType`.

**Comment by AlmogRnD** [comment]
I'm closing went with a different package, having to many issues with this thanks
