### ISSUE TITLE
undefined is not an object (evaluating 'ReactPropTypes.string')

### ISSUE THREAD

**Issue by z364253151** [testshallpass/react-native-dropdownalert#87]
#### Issue Description

undefined is not an object (evaluating 'ReactPropTypes.string')

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

### Additional Information

* React Native version: [0.45-0.47]
* react-native-dropdownalert version: [2.11.0]
* Platform(s) (iOS, Android, or both?): [both]

**Comment by testshallpass** [comment]
Closing lack of detail.
