### ISSUE TITLE
IOS closeInterval problem when it is greater than 1000ms

### ISSUE THREAD

**Issue by MichaelPintos** [testshallpass/react-native-dropdownalert#90]
#### Issue Description

when the property is greater than 1500ms the alert does not disappear

#### Steps to Reproduce / Code Snippets
`<DropdownAlert ref={ref => (this.dropdown = ref)} closeInterval={1500}/>`

set the property with a value greater than 1000ms

### Additional Information

* React Native version: 0.46.4
* react-native-dropdownalert version: 2.11.0
* Platform(s) (iOS, Android, or both?):  IOS 10.3.3 IPHONE 5   `physical device`

**Comment by kylanhurt** [comment]
Why was this issue closed?
