### ISSUE TITLE
Set "replaceEnabled" to false, alert won't show up

### ISSUE THREAD

**Issue by wellyshen** [testshallpass/react-native-dropdownalert#94]
#### Issue Description

Thank you for this great library. When I set the `replaceEnabled` to false. The alert component won't show up. But it works fine when the `replaceEnabled` set to true.

#### Steps to Reproduce / Code Snippets

```javascript
import React from 'react';
import type { Element } from 'react';
import DropdownAlert from 'react-native-dropdownalert';

import styles from './Toast.styles';

type Props = { setRef: (ref: any) => void };

export default ({ setRef }: Props): Element<any> => (
  <DropdownAlert
    containerStyle={styles.container}
    messageStyle={styles.message}
    closeInterval={3500}
    updateStatusBar={false}
    replaceEnabled={false}  // <== The alert will show up when it set to "true"
    ref={ref => setRef(ref)}
  />
);
```

#### Expected Results

Alert show up and animation won't dismiss while message changed.

### Additional Information

* React Native version: 0.48.4
* react-native-dropdownalert version: 3.1.0
* Platform(s) (iOS, Android, or both?): iOS
* xCode version: 9
* iOS version: 11.0.1

**Comment by testshallpass** [comment]
It looks like the animation routine is not invoked when `false`.  I'll fix it up. 

```javascript
      if (this.state.isOpen == false) {
        this.animate(1);
      }
```

**Comment by wellyshen** [comment]
Hi @testshallpass Any update for this issue?

**Comment by testshallpass** [comment]
Sorry for the delay. I must have initially interpreted the issue wrong. I am not able to reproduce it.

**Comment by wellyshen** [comment]
@testshallpass 

Here's my steps:
1. Set `replaceEnabled={false}` at beginning
2. Use method `alertWithType()` to display toast
3. Toast won't be show <= If this behavior meet expectation?
