### ISSUE TITLE
Request: Add ability to change font

### ISSUE THREAD

**Issue by rajivshah3** [testshallpass/react-native-dropdownalert#97]
#### Issue Description

Ability to change font

### Additional Information

* React Native version: 
* react-native-dropdownalert version: 0.0.6
* Platform(s) (iOS, Android, or both?): Both
There should be the ability to change fonts in the alerts

**Comment by testshallpass** [comment]
Hi @rajivshah3 The module never was v0.0.6.  And you can change font by using `titleStyle` and `messageStyle` props.

**Comment by rajivshah3** [comment]
Whoops, read the wrong package. Meant 2.11.
I don't see any option to change the font in DropdownAlert.js however. I'm looking to change from the default font to Lato Regular

**Comment by testshallpass** [comment]
Hi @rajivshah3  You can pass in `Text.propTypes.style` objects to the props I mentioned. 

For example, 

```javascript
{ fontSize: 16, 
textAlign: 'left', 
fontWeight: 'bold', 
color: 'white', 
backgroundColor: 'transparent', 
fontFamily: 'Lato Regular' } // make sure font name matches the one you want (case sensitive) 
```

for more styles: http://facebook.github.io/react-native/releases/0.46/docs/textstyleproptypes.html

**Comment by rajivshah3** [comment]
Thank you so much!
