### ISSUE TITLE
Change image for certain type

### ISSUE THREAD

**Issue by rajivshah3** [testshallpass/react-native-dropdownalert#99]
How can I change the icon of a certain type of dropdown (e.g. change the sun on success to a checkmark)? I see the imageSrc prop but I can't tell if that will change the image across all types or just the one I want to change

**Comment by testshallpass** [comment]
Hi @rajivshah3 So the `imageSrc` will only be applied to the `custom` type. It can be a url or local asset.

**Comment by alfredoyong** [comment]
Can the image be specified when calling alertWithType? For example, when somebody is sending you a message and the app is displaying the alert, showing the other users' picture

**Comment by testshallpass** [comment]
Hi @alfredoyong  
> Can the image be specified when calling alertWithType? 

In short alertWithType does not accept imageSrc as param. However, you can change the imageSrc on a state change for each display of the alert.
